"""Bundle authored module traces and practical tasks; fail on missing coverage."""
import json
from pathlib import Path
from module_walkthroughs import WALKTHROUGHS
from database_courses import COURSES

ROOT=Path(__file__).resolve().parents[1]
catalog=json.loads((ROOT/'assets/curriculum/catalog.json').read_text(encoding='utf-8'))
db={c['id']:c for c in COURSES}
result={}
for course in catalog:
    if course['id']=='python': continue  # Existing detailed playable foundations.
    for i,module in enumerate(course['modules']):
        if i >= 6:
            trace=module['explanation']
        elif course['id'] in db:
            trace=db[course['id']]['modules'][i]['trace']
        else:
            trace=WALKTHROUGHS[course['id']][i]['en']
        result[module['plans'][0]['id']]={'trace':trace,'practice':module['practice'],'review':module['plans'][0]['evidence']}
expected=sum(len(course['modules']) for course in catalog if course['id']!='python')
assert len(result)==expected
payload=json.dumps(result,ensure_ascii=False)
(ROOT/'assets/curriculum/module_guides.json').write_text(json.dumps(result,ensure_ascii=False,indent=2),encoding='utf-8')
(ROOT/'lib/data/module_guides.dart').write_text("// Generated by tool/build_module_guides.py.\nimport 'dart:convert';\nfinal Map<String,dynamic> moduleGuides = jsonDecode(r'''"+payload+"''') as Map<String,dynamic>;\n",encoding='utf-8')
print(f'Bundled {len(result)} worked module explanations.')
