"""Original curriculum source. Regenerate bundled Dart and Markdown with Python 3.
No downloads or third-party Python packages. IDs are stable backup identifiers.
"""
import json
from beginner_lessons import GUIDES
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
courses = []

def course(id, title, prerequisites, tools, modules, projects):
    result = dict(id=id, title=title, prerequisites=prerequisites.split(), tools=tools, modules=[], projects=[])
    for i, (name, explanation, example, challenge) in enumerate(modules, 1):
        levels = [('remember', 'understand'), ('understand', 'apply'), ('apply', 'analyze'), ('analyze', 'evaluate'), ('evaluate', 'create'), ('create', 'evaluate')][min(i-1, 5)]
        objectives = {
            'remember': f'Identify the key terms and syntax in {name.lower()} without consulting the example.',
            'understand': f'Explain how {name.lower()} changes program behavior using a traced example.',
            'apply': f'Implement {challenge[0].lower() + challenge[1:]}',
            'analyze': f'Locate a failing assumption in {name.lower()} and isolate it with a minimal reproduction.',
            'evaluate': f'Judge two approaches to {name.lower()} against correctness, maintainability, and offline operation.',
            'create': f'Design and deliver an original extension using {name.lower()} with explicit acceptance tests.'}
        plans = []
        for j, level in enumerate(levels, 1):
            plans.append(dict(id=f'{id}-m{i}-l{j}', title=f'{name}: '+('guided investigation' if j == 1 else 'independent studio'), level=level,
                minutes=60 if j == 1 else 90, objective=objectives[level],
                activity=(f'Read the explanation. Trace the worked example on paper, record each state change, then run it using the course toolchain. {challenge} Compare the actual result with your prediction.' if j == 1 else f'{challenge} Change one requirement, implement your own solution, then deliberately introduce an edge-case failure. Diagnose and repair it without copying the worked example.'),
                evidence={
                    'remember':'Submit five correctly defined terms and label their occurrences in the example; correct at least four before continuing.',
                    'understand':'Submit a state trace and a causal explanation of two outputs. Explain a changed input without running it first.',
                    'apply':'Submit source and normal, empty, and invalid input results. Each stated acceptance condition must pass.',
                    'analyze':'Submit the failing case, root cause, minimal fix, and a regression test that fails before the fix and passes after.',
                    'evaluate':'Submit a comparison of two designs, evidence from tests, one limitation of the chosen design, and a reasoned decision.',
                    'create':'Submit your own requirements, design, source, test evidence, and a short demonstration. Explain how your extension differs from the example.'}[level]))
        result['modules'].append(dict(title=name, explanation=explanation, example=example, plans=plans))
    for i, (name, brief, requirements) in enumerate(projects, 1):
        result['projects'].append(dict(id=f'{id}-p{i}',title=name,brief=brief,hours=[6,12,24][i-1],requirements=requirements,
            milestones=['Discover: write three user stories, scope exclusions, and acceptance examples using fictional data.',
                        'Design: sketch components and data flow; justify one tradeoff in an architecture decision record.',
                        'Build: implement the required behaviors in small reviewable changes; record how to reproduce the build offline.',
                        'Verify: test every acceptance condition, empty/invalid data, and restart behavior; retain results.',
                        'Review: demonstrate to a peer or conduct a recorded self-review; document feedback, improvements, and limitations.']))
    courses.append(result)

course('python','Python Course Zero to Hero','', 'Python basics run in the app’s limited sandbox. Advanced modules require a separately installed CPython 3 interpreter; use only the standard library. Save local .py files and run python filename.py. No pip packages are needed for these projects.', [
('Values, decisions, and loops','Variables name values; conditionals select a branch and loops repeat a rule. Trace one iteration at a time. Validate that a quantity is nonnegative before calculating a total. Complete the seven interactive Python foundation lessons before this studio.','prices = [20, 35, 15]\ntotal = 0\nfor price in prices:\n    total = total + price\nprint(total)','a shopping total that rejects negative quantities.'),
('Functions and data structures','Separate calculation from input and output. Lists preserve sequence; dictionaries associate unique keys with values; sets remove duplicates. A pure function produces a result without modifying shared state.','def total(items):\n    return sum(item["price"] * item["quantity"] for item in items)\nassert total([]) == 0','an inventory summary using dictionaries and functions with tests for duplicate item names.'),
('Files, exceptions, and modules','Use context managers to close files even when reading fails. JSON carries structured data, but parsing does not validate its business meaning. Catch a specific exception and preserve the previous valid file when a write fails.','import json\nfrom pathlib import Path\npath = Path("items.json")\npath.write_text(json.dumps([{ "name": "Notebook", "stock": 4 }]), encoding="utf-8")\nprint(json.loads(path.read_text(encoding="utf-8")))','a JSON importer that reports malformed data without erasing the last valid records.'),
('Objects, typing, and iterators','A class groups state and invariants. Prefer composition when behavior can be delegated. Type hints communicate contracts; they do not enforce values at runtime. Generators yield records incrementally instead of building an entire result list.','from dataclasses import dataclass\n@dataclass(frozen=True)\nclass Item:\n    name: str\n    stock: int\n\ndef available(items):\n    for item in items:\n        if item.stock > 0:\n            yield item','an immutable item model and a generator that filters available stock without altering the source.'),
('SQLite, testing, and architecture','Put persistence behind a repository interface so calculations can be tested without a database. SQL placeholders separate values from commands. A transaction groups related changes; rollback prevents a half-recorded sale. Use unittest for boundary and regression cases.','import sqlite3\nwith sqlite3.connect(":memory:") as db:\n    db.execute("CREATE TABLE stock (name TEXT PRIMARY KEY, quantity INTEGER)")\n    db.execute("INSERT INTO stock VALUES (?, ?)", ("Notebook", 4))\n    assert db.execute("SELECT quantity FROM stock").fetchone()[0] == 4','a transactional stock sale that rolls back when requested quantity exceeds availability.'),
('Concurrency, profiling, and delivery','A worker can keep an interface responsive, but shared mutable data introduces races. Compare sequential work with an executor using measured timings. Profile before optimizing, keep SQLite ownership explicit, and distribute a README and reproducible standard-library tests.','from concurrent.futures import ThreadPoolExecutor\ndef summarize(values):\n    return sum(values)\nwith ThreadPoolExecutor(max_workers=2) as pool:\n    print(list(pool.map(summarize, [[1, 2], [3, 4]])))','a batch report with sequential and worker implementations, measuring time and checking equal results.')], [
('Household expense ledger','Help a fictional family understand weekly spending in AFN.',['Add dated expenses in integer AFN with a category.','Reject negative amounts and blank categories.','Produce category totals and a weekly total from local JSON.']),
('School attendance analyst','Help a teacher summarize attendance from a local CSV file.',['Validate student IDs, dates, and duplicate rows.','Calculate attendance percentages with a defined zero-session rule.','Export a UTF-8 report and test malformed CSV cases.']),
('Community shop inventory','Build an offline stock and sales tool for a small stationery shop.',['Persist items and sales in SQLite; use an atomic sale transaction.','Prevent overselling and retain stock after restart.','Provide low-stock reports, JSON export, and automated regression tests.'])])

course('web-design','Web Design','', 'Use a local text editor and browser. Open index.html directly; bundle CSS, images, and fonts locally. No CDN, online design service, or package manager is required.',[
('Semantic HTML','A page is a document before it is a visual composition. Landmarks, headings, lists, and labels express relationships to browsers and assistive tools. Choose elements by meaning, then style them.','<main>\n  <h1>Community library</h1>\n  <nav aria-label="Sections"><a href="#hours">Opening hours</a></nav>\n  <section id="hours"><h2>Hours</h2><p>Saturday–Thursday, 9–4</p></section>\n</main>','a library page with a meaningful heading hierarchy and working internal navigation.'),
('CSS cascade and typography','The cascade resolves competing declarations; inheritance passes selected values to descendants. Use a small spacing and color system instead of unrelated numbers. Relative units support larger text settings.','body { font: 1rem/1.6 system-ui, sans-serif; margin: 0; }\nmain { max-width: 65ch; margin-inline: auto; padding: 1.5rem; }\na:focus-visible { outline: 3px solid #175c40; }','a readable type and spacing system with visible keyboard focus.'),
('Responsive layout','Flexbox aligns a row or column; Grid coordinates two dimensions. Let content choose breakpoints. Avoid fixed heights that clip translated or enlarged text, and test the narrowest supported viewport.','.cards { display: grid; gap: 1rem; grid-template-columns: repeat(auto-fit, minmax(min(100%, 16rem), 1fr)); }','a card layout that reflows at 320, 768, and 1280 CSS pixels without horizontal overflow.'),
('Forms and accessibility','Labels identify fields; instructions and error messages explain how to recover. Native controls provide useful keyboard behavior. Do not use color alone to indicate an error. HTML validation helps users but is not server-side security.','<label for="name">Student name</label>\n<input id="name" name="name" required aria-describedby="name-help">\n<p id="name-help">Enter the name used on your school record.</p>','a registration form with labels, keyboard access, and understandable required-field errors.'),
('RTL and inclusive design','Set direction on the relevant document or region. Logical properties such as margin-inline adapt to direction; source-code blocks remain left-to-right. Test mixed numbers, names, and long translations with native readers before release.','<article lang="fa" dir="rtl"><h1>کتابخانه</h1><p>ساعت کار: ۹ تا ۴</p></article>\n<pre dir="ltr">print("Salam")</pre>','an English and Dari page pair with logical spacing and a documented translation review checklist.'),
('Design systems and usability','Reusable tokens and components reduce accidental variation. Evaluate a design through tasks: can a learner locate hours, navigate with a keyboard, and read at 200% zoom? Record observed difficulties and revise one component at a time.',':root { --space: 1rem; --ink: #162f28; --surface: #fffdf5; }\n.card { padding: var(--space); color: var(--ink); background: var(--surface); }','a small component guide and a usability report with three observed issues and fixes.')],[
('Student portfolio','Present a fictional student’s work in an accessible local website.',['Use semantic sections and local images with appropriate alternative text.','Provide keyboard navigation and a printable résumé.','Remain readable at 320px width and 200% zoom.']),
('Bilingual school information site','Make school schedules understandable in English and Dari.',['Create two local language pages with correct direction.','Include timetables with table headings and clear dates.','Use no external fonts, scripts, or image requests.']),
('Community services design system','Create an accessible site for library, training, and community events.',['Deliver reusable navigation, cards, forms, and typography tokens.','Document responsive states and error states.','Conduct three task-based usability checks and record revisions.'])])

course('web-development','Web Development','web-design javascript nodejs expressjs','Provision a browser, Node.js, Express, and the package cache in advance. Run client and server on the same computer using loopback. Localhost is used for practice; no internet service is required.',[
('Client, server, and HTTP','The browser requests resources; a server returns a status, headers, and a body. A local server is still a server, even without internet. Distinguish persistent data from the rendered document.','GET /books HTTP/1.1\nHost: 127.0.0.1:3000\n\nHTTP/1.1 200 OK\nContent-Type: application/json\n\n[{"id":1,"title":"Algorithms"}]','a sequence diagram connecting a search interaction to a local HTTP response.'),
('Forms and API contracts','Agree on request and response shapes before wiring the interface. Validate at the server boundary and render field errors near their controls. A successful HTTP transport does not imply a valid business operation.','const response = await fetch("/api/books");\nif (!response.ok) throw new Error("Could not load books");\nconst books = await response.json();','a book form with both client hints and server validation errors.'),
('Relational modeling and transactions','Model entities with stable IDs and constraints. A loan links a member and a book; an atomic transaction must prevent two active loans for the same copy. Schema changes need migrations and rollback plans.','CREATE TABLE books (id INTEGER PRIMARY KEY, title TEXT NOT NULL);\nCREATE TABLE loans (id INTEGER PRIMARY KEY, book_id INTEGER NOT NULL REFERENCES books(id), returned_at TEXT);','a library schema and a transaction design that prevents duplicate active loans.'),
('Security boundaries','Treat all input as untrusted. Authorization belongs on the server for each operation. Escape text when rendering HTML, parameterize database queries, and never store plaintext passwords. For this offline learning project, use fictional roles without claiming production authentication.','const titleNode = document.createElement("span");\ntitleNode.textContent = userSuppliedTitle;','a threat model covering stored script injection, unauthorized edits, and unsafe file paths.'),
('Testing and fault recovery','Test contracts between layers, not only isolated helpers. Simulate a failed write and an unavailable server. Display recoverable errors while preserving the user’s unsaved input. A retry must not silently create duplicate records.','const operation = { id: "request-001", bookId: 7 };\n// Persist and deduplicate operation.id in the same transaction as the loan.','an idempotent loan request and tests for retry after an ambiguous response.'),
('Offline packaging and maintainability','An offline package includes the client, server, database initialization, dependencies, and instructions. Separate domain rules from HTTP and storage. Build on a clean provisioned machine without fetching assets; document installation separately from runtime.','project/\n  domain/loan.js\n  adapters/http.js\n  adapters/storage.js\n  public/index.html\n  test/loan.test.js','a reproducible local release with seed data, migration instructions, and an airplane-mode acceptance report.')],[
('Local event registration','Manage seats for a fictional workshop on one local computer.',['Validate attendee input and capacity.','Show inline errors without discarding form values.','Export a registration list using fictional data.']),
('Library lending system','Track books and loans through a browser and local service.',['Prevent duplicate active loans and support returns.','Persist records and provide search and pagination.','Test API contracts and database rollback behavior.']),
('Training center administration','Integrate courses, enrollments, and attendance in a local full-stack app.',['Separate domain, API, and persistence responsibilities.','Enforce capacity and role rules on the server.','Ship installation instructions, migration tests, and a local backup workflow.'])])

course('java','Java','', 'Install a JDK before going offline. Use javac Main.java and java Main for plain examples. Provision build tools and any test libraries beforehand; initial projects can use Java assertions with java -ea Main.',[
('Types and control flow','Java checks declared types at compile time. Use integers for whole quantities and choose explicit rounding for money. A loop invariant states what remains true after every iteration.','public class Main { public static void main(String[] args) { int total = 0; for (int value : new int[]{10,20,30}) total += value; System.out.println(total); } }','a marks summary with bounds checks and a stated loop invariant.'),
('Classes and encapsulation','Keep mutable fields private and expose operations that preserve invariants. Constructors establish valid state. An interface describes a capability without fixing its implementation.','final class Stock { private int quantity; Stock(int q) { if(q < 0) throw new IllegalArgumentException(); quantity=q; } int quantity() { return quantity; } }','a stock object that cannot be initialized with a negative quantity.'),
('Collections and generics','List preserves order, Set expresses uniqueness, and Map associates keys with values. Generics reject incompatible element types during compilation. Define equality deliberately when objects become map keys.','java.util.Map<String,Integer> stock = new java.util.HashMap<>();\nstock.put("Notebook", 5);\nstock.merge("Notebook", 2, Integer::sum);','a catalog with unique IDs, duplicate detection, and sorted reports.'),
('Exceptions and file persistence','A checked exception makes a failure path visible in an API. Try-with-resources closes owned resources. Separate malformed user data from unavailable storage so recovery messages are specific.','try (var lines = java.nio.file.Files.lines(java.nio.file.Path.of("items.txt"))) { lines.filter(s -> !s.isBlank()).forEach(System.out::println); }','a file importer that reports line numbers and preserves valid existing records.'),
('Streams, concurrency, and tests','Streams express transformations but side effects make reasoning harder. Executors separate task submission from thread creation. Protect shared state or avoid it; test deterministic domain functions separately from scheduling.','var names = java.util.List.of("Kabul", "Herat", "Bamyan");\nvar sorted = names.stream().sorted().toList();\nassert sorted.size() == 3;','a report pipeline and compare sequential and concurrent results under repeated runs.'),
('SOLID and delivery','Dependency inversion lets business rules depend on a repository contract. A memory adapter supports fast tests; a file adapter supports persistence. Keep interfaces small and package a command-line entry point with reproducible execution instructions.','interface ItemRepository { java.util.List<String> allNames(); }\nfinal class Report { private final ItemRepository repository; Report(ItemRepository r) { repository=r; } int count() { return repository.allNames().size(); } }','a repository-backed report with fake storage and failure-path tests.')],[
('Student gradebook','Produce course results from fictional marks.',['Validate marks from 0 to 100.','Calculate averages with a documented rounding rule.','Test empty classes and boundary marks.']),
('Library desktop core','Implement the domain and command-line interface of a library.',['Use stable IDs for books and members.','Reject borrowing an unavailable copy.','Persist to local files and report malformed records.']),
('Warehouse ledger','Maintain stock movements for a small warehouse.',['Encapsulate stock invariants and provide repository adapters.','Generate sorted reports and reconcile movement totals.','Test failure recovery and document the build and packaging steps.'])])

course('kotlin','Kotlin','', 'Provision Kotlin/JVM and a JDK. Compile local code with kotlinc Main.kt -include-runtime -d main.jar, then java -jar main.jar. Coroutine libraries and Gradle dependencies, if used, must be cached before offline study.',[
('Values, expressions, and nullability','Prefer val for bindings that do not change. A nullable type makes absence explicit; a safe call propagates null, while the Elvis operator supplies a fallback. Avoid force-unwrapping input that can be absent.','fun main() { val name: String? = null; println(name?.uppercase() ?: "Guest") }','a greeting and fee calculator that handles missing optional input.'),
('Functions and collections','Small functions can transform immutable lists. map changes each element, filter retains matching elements, and fold accumulates a result. Explain when a sequence avoids intermediate collections and when it adds overhead.','val total = listOf(10, 20, 30).filter { it > 10 }.fold(0) { sum, n -> sum + n }','a purchase report using collection transformations and an empty-list test.'),
('Data classes and sealed results','A data class represents values; a sealed hierarchy enumerates alternatives. A when expression can handle each result explicitly, making missing cases visible when the model changes.','sealed interface SaveResult\ndata class Saved(val id: Int) : SaveResult\ndata class Rejected(val reason: String) : SaveResult','a validation API that returns a typed success or failure instead of ambiguous null.'),
('Extensions, interfaces, and generics','Extensions add convenient syntax without changing a type’s actual members. Interfaces define replaceable behavior. Keep transformations separate from storage and pass dependencies to constructors for testability.','interface Repository<T> { fun all(): List<T> }\nfun String.normalizedName(): String = trim().lowercase()','a generic repository and duplicate-name detection with explicit normalization rules.'),
('Coroutines and structured concurrency','Suspending is not the same as blocking a thread. A coroutine scope owns child work and cancellation. Dispatch blocking IO appropriately and propagate cancellation; do not swallow it inside a broad failure handler.','// Requires a provisioned kotlinx-coroutines dependency.\nsuspend fun loadNames(repository: NameRepository): List<String> = repository.load()\ninterface NameRepository { suspend fun load(): List<String> }','a cancellable report operation with deterministic fake-repository tests.'),
('Testing and JVM interoperability','Kotlin can call Java APIs, but platform types weaken null guarantees. Validate values at the boundary. Separate a functional core from file operations, and test both pure rules and persistence round trips.','fun validStock(value: Int): Boolean = value >= 0\nfun main() { check(validStock(0)); check(!validStock(-1)) }','a command-line release with boundary tests, persistence checks, and a Java API adapter.')],[
('Study planner','Organize weekly study tasks.',['Model optional deadlines safely.','Filter tasks by course and completion.','Test empty and duplicate task input.']),
('Expense categorizer','Summarize local expense records.',['Use typed validation results and immutable models.','Import a local file with useful errors.','Generate category totals and test malformed records.']),
('Offline inventory core','Create a reusable Kotlin inventory library and CLI.',['Expose repository contracts and typed operations.','Support cancellation for long reports with provisioned coroutine tools.','Deliver tests, local persistence, and JVM execution instructions.'])])

course('android','Android','kotlin','Provision Android Studio, JDK, Android SDK, emulator image or device drivers, and all Gradle/Compose/Room dependencies. Use Gradle offline mode after provisioning. The learning app cannot compile Android projects itself.',[
('Android project and lifecycle','An Activity is a platform entry point, not a permanent store. Configuration changes can recreate it. Identify manifest declarations, resources, build variants, and the difference between app process lifetime and screen lifetime.','class MainActivity : androidx.activity.ComponentActivity() {\n override fun onCreate(state: android.os.Bundle?) {\n  super.onCreate(state)\n  setContent { androidx.compose.material3.Text("Salam") }\n }\n}\n// In a Compose project, import androidx.activity.compose.setContent.','a local Android screen and describe what survives rotation and process recreation.'),
('Compose state and layouts','Composable functions describe UI from state. Hoist state when multiple components need one source of truth. remember holds state across recomposition; persistent and restorable state require a deliberate owner.','@Composable\nfun Counter() {\n var count by rememberSaveable { mutableIntStateOf(0) }\n Button(onClick = { count++ }) { Text("Count: $count") }\n}\n// Import Compose runtime, saveable, and Material3 symbols.','a counter and form that preserve appropriate fields after rotation.'),
('Navigation and ViewModel','Navigation identifies destinations and arguments; a ViewModel owns screen logic. Expose UI state and accept user actions. Pass stable IDs between destinations instead of serializing mutable database entities.','data class UiState(val names: List<String> = emptyList(), val error: String? = null)\n// A ViewModel exposes StateFlow<UiState>; the UI collects with lifecycle awareness.','a list-to-detail flow with loading, empty, content, and error states.'),
('Room and repository boundaries','Room maps structured data to SQLite. Entities express storage, DAOs express queries, and repositories expose application operations. Use migrations when schemas change and keep writes off the UI thread.','@Entity\ndata class Note(@PrimaryKey val id: Long, val text: String)\n@Dao\ninterface Notes { @Query("SELECT * FROM Note ORDER BY id") fun observe(): Flow<List<Note>> }\n// Requires Room and Flow imports and provisioned code generation.','a note repository with a migration test and a restart persistence check.'),
('Background work and permissions','Request only capabilities needed for an explicit feature. Long deferred work and immediate screen work have different owners. A background task may retry, so its effects must be idempotent. A local-only app needs no internet permission.','// Background export state: queued -> running -> succeeded | failed.\n// Store an operation ID; a repeated export must not duplicate ledger entries.','an export workflow that reports cancellation and retries without duplicating data.'),
('Accessibility, testing, and release','Test domain rules, Compose interactions, and device lifecycle behavior separately. Provide labels and adequate touch targets. An unsigned or debug build is not a production release; document signing ownership and test an installed build in airplane mode.','@Test fun emptyNameIsRejected() { assertFalse(validateName("")) }\nfun validateName(name: String) = name.isNotBlank()','an accessible release candidate with lifecycle tests and a documented offline installation path.')],[
('Campus timetable','Help students view a local weekly timetable.',['Build accessible Compose day and class views.','Preserve selected day through rotation.','Bundle all timetable data locally.']),
('Study notes','Create searchable notes on a device.',['Persist with Room and edit by stable ID.','Handle empty content and migration failures.','Test search, restart, rotation, and larger font sizes.']),
('Community inventory Android app','Track goods on one shared learning device using fictional data.',['Separate ViewModel, domain operations, and repository adapters.','Prevent invalid stock adjustments and persist transaction history.','Support local export and demonstrate installed airplane-mode operation.'])])

course('ios','iOS','swift','Native iOS development requires a compatible Mac with Xcode, SDKs, and simulator runtimes provisioned beforehand. Simulator exercises can be local; physical-device signing and distribution have separate Apple requirements. Windows or Android alone cannot build these native projects.',[
('Xcode and app lifecycle','An iOS app has scenes and lifecycle transitions. Treat backgrounding as a normal event, not an error. Separate the application entry point from feature views and inspect the project’s target settings.','import SwiftUI\n@main struct LearningApp: App { var body: some Scene { WindowGroup { Text("Salam") } } }','a simulator app and a diagram of active, inactive, and background transitions.'),
('SwiftUI state and composition','A view describes a value-dependent interface. State has an owner, bindings allow controlled editing, and child views should receive only what they need. Keep calculations outside the body when they represent domain policy.','struct Counter: View { @State private var count = 0; var body: some View { Button("Count: \\(count)") { count += 1 } } }','a composed form with validation and one clear owner for each mutable value.'),
('Navigation and accessible forms','NavigationStack models a navigation path. Stable identifiers connect list and detail screens. VoiceOver labels and Dynamic Type are design inputs; use system controls before inventing custom interaction patterns.','NavigationStack { List(["Algorithms", "Databases"], id: \\.self) { name in NavigationLink(name) { Text(name) } } }','a course list and detail flow that remains usable with VoiceOver and large text.'),
('Local persistence and migrations','Choose storage by data shape. Codable files fit small documents; structured persistence fits related records and queries. Decode into validated models, preserve the last good file, and test version changes with real fixtures.','struct Note: Codable { let id: UUID; var text: String }\nlet data = try JSONEncoder().encode([Note(id: UUID(), text: "Study")])\n// Persist data atomically in the application documents directory.','a local note store with corrupted-file recovery and a schema-version fixture.'),
('Concurrency and platform boundaries','UI updates belong to the main actor. Asynchronous work should cancel when its owner no longer needs the result. Wrap platform file operations behind a protocol so failure and cancellation can be tested without the UI.','protocol NoteStore { func load() async throws -> [Note] }\n@MainActor final class NoteModel { var notes: [Note] = []; func refresh(using store: NoteStore) async throws { notes = try await store.load() } }','a cancellable load flow with visible recovery and a fake failing store.'),
('Testing and distribution planning','Use unit tests for policy and UI tests for critical flows. Verify background/foreground transitions and offline relaunch. Build archives, signing, and distribution are separate from coding; record the environment and limits of what was tested.','import XCTest\nfinal class TitleTests: XCTestCase { func testBlankTitle() { XCTAssertTrue(" ".trimmingCharacters(in: .whitespaces).isEmpty) } }','a tested simulator release with an explicit signing and physical-device verification checklist.')],[
('Campus guide for iOS','Provide local campus information without maps or web services.',['Bundle place descriptions and accessibility information.','Support Dynamic Type and VoiceOver.','Use local navigation without network requests.']),
('Reading journal','Track books and reading notes.',['Persist Codable documents atomically.','Support edit, search, and safe delete confirmation.','Test corrupted files and app relaunch.']),
('Workshop organizer','Manage fictional workshops and attendance locally.',['Enforce capacities through domain logic.','Provide accessible list, detail, and attendance flows.','Use repository tests and demonstrate simulator operation offline.'])])

course('swift','Swift','', 'Provision a supported Swift toolchain. Use swift main.swift for basic programs and swift test for package tests. Foundation availability varies by platform; iOS UI work belongs to the iOS course and requires Xcode on macOS.',[
('Values, control flow, and optionals','Swift distinguishes absent values with Optional. Use conditional binding or guard to handle absence. let prevents rebinding, while value types help avoid accidental shared mutation.','let input = "42"\nif let amount = Int(input) { print(amount + 1) } else { print("Invalid amount") }','an integer parser with explicit invalid-input behavior.'),
('Functions and collections','Functions state parameter and return types. Arrays preserve order, dictionaries map keys, and sets express uniqueness. Separate transformations from IO and prefer readable intermediate names over dense chains.','func total(_ values: [Int]) -> Int { values.reduce(0, +) }\nassert(total([]) == 0)','a grade summary with empty and boundary cases.'),
('Structs, enums, and protocols','Structs have value semantics; classes share reference identity. Enums can carry associated values to model outcomes. Protocols express capabilities and let code depend on behavior instead of a concrete implementation.','enum Validation { case accepted(Int); case rejected(String) }\nstruct Item { let id: Int; var quantity: Int }','a stock validation result and compare copied structs with shared class instances.'),
('Errors, Codable, and generics','Throwing functions make failure explicit. Codable handles representation, not domain validity. Generic algorithms share behavior across types while retaining compiler checks. Validate decoded values before accepting them.','import Foundation\nstruct Expense: Codable { let amount: Int }\nlet bytes = try JSONEncoder().encode(Expense(amount: 20))\nprint(try JSONDecoder().decode(Expense.self, from: bytes).amount)','a JSON import that distinguishes malformed bytes from invalid amounts.'),
('ARC and concurrency','Automatic reference counting manages object lifetimes, but strong reference cycles can keep objects alive. Actors isolate mutable state; async does not guarantee parallel work. Choose ownership before adding weak references or detached tasks.','actor Counter { private var value = 0; func increment() { value += 1 }; func read() -> Int { value } }','an actor-based counter and an ownership diagram for a callback retaining its owner.'),
('Packages, tests, and design','Swift packages organize modules and tests. Hide file access behind a protocol, keep domain models independent, and document public contracts. Compare alternative abstractions with a concrete change request instead of counting patterns.','protocol LedgerStore { func amounts() throws -> [Int] }\nfunc balance(_ store: LedgerStore) throws -> Int { try store.amounts().reduce(0, +) }','a package with a fake store, tested failure paths, and a local usage example.')],[
('AFN budget calculator','Calculate a fictional household budget.',['Use integer amounts and validated input.','Report remaining budget and overspending.','Test zero and negative input policies.']),
('Book catalog CLI','Maintain a local reading catalog.',['Model books with stable identifiers and Codable.','Support search and duplicate rejection.','Preserve previous data on import failure.']),
('Reusable ledger package','Deliver a Swift package for financial record exercises using fictional data.',['Separate domain rules and storage protocols.','Handle concurrent operations with explicit isolation.','Provide tests, API documentation, and a local command-line client.'])])

course('cpp','C++','', 'Provision a C++17-capable compiler and local standard library. Compile with g++ -std=c++17 -Wall -Wextra main.cpp -o app or the equivalent MSVC/Clang command. Sanitizers are optional and must be provisioned; no external libraries are required.',[
('Types, expressions, and loops','C++ types affect ranges and operations. Integer division discards fractional parts. Initialize values before reading them, check input failures, and avoid assuming signed overflow wraps predictably.','#include <iostream>\nint main() { int total = 0; for (int n : {10,20,30}) total += n; std::cout << total << "\\n"; }','a marks calculator that checks input and documents its numeric range.'),
('Functions, references, and const','Pass small values by value and large read-only objects by const reference. A reference refers to an existing object; it must not outlive that object. Express whether a function can mutate its input.','#include <vector>\nint sum(const std::vector<int>& values) { int result=0; for(int value:values) result+=value; return result; }','a report function with a clear ownership and mutation contract.'),
('RAII and object lifetimes','RAII ties resource release to object lifetime. Prefer standard containers and smart pointers to manual new/delete. Destructors run during stack unwinding; a dangling pointer remains invalid even if its old bytes look plausible.','#include <memory>\nstruct Item { int stock=0; };\nauto item = std::make_unique<Item>();\n// The unique owner releases the Item when it leaves scope.','a resource ownership diagram and replace manual allocation with an RAII owner.'),
('STL algorithms and complexity','Choose a container based on required operations and measured scale. Sorting generally costs more than one linear scan. Algorithms accept iterator ranges; invalidating an iterator while using it can introduce subtle defects.','#include <algorithm>\n#include <vector>\nstd::vector<int> values{3,1,2};\n// Inside a function:\n// std::sort(values.begin(), values.end());','a sorted inventory search and compare linear search with binary search on ordered data.'),
('Files, exceptions, and testing','Check stream state after IO and preserve the last good data when parsing fails. Assertions are useful in tests, but release builds may disable them; never use assert as the only user-input validation.','#include <sstream>\n#include <stdexcept>\nint parse(const std::string& text) { std::istringstream in(text); int n; if(!(in >> n)) throw std::invalid_argument("integer required"); in >> std::ws; if(!in.eof()) throw std::invalid_argument("trailing data"); return n; }','a strict record parser with empty, overflow, and trailing-data cases.'),
('Templates, boundaries, and profiling','Templates reuse type-safe algorithms; keep diagnostics and interfaces understandable. Separate file storage from calculations, inspect compiler warnings, and measure before optimizing. Use sanitizers where available to investigate lifetime errors.','template<class T> T larger(T a, T b) { return a < b ? b : a; }\n// Define domain rules in a library and inject storage through an interface.','a modular release with warning-clean builds, test evidence, and a measured optimization decision.')],[
('Exam statistics CLI','Summarize fictional exam scores.',['Reject out-of-range marks and invalid tokens.','Calculate minimum, maximum, and mean with an empty-input rule.','Compile with warnings enabled and retain test results.']),
('Library search index','Search a local catalog efficiently.',['Load and validate records from a file.','Compare linear and sorted search using the same fixture.','Avoid dangling references during updates.']),
('Warehouse stock engine','Build a C++ inventory core and CLI.',['Use RAII and clear ownership contracts.','Prevent invalid stock transitions and preserve files after errors.','Deliver modular source, boundary tests, and profiling notes.'])])

course('javascript','JavaScript','web-design','Use a browser’s developer tools for pure language examples and local HTML with classic scripts. ES modules and fetch may require a provisioned local server. Node.js is optional for node --test; no remote scripts are needed.',[
('Values, scope, and control flow','const prevents rebinding; it does not freeze an object. Use strict equality to avoid implicit coercion surprises. Block scope limits where a binding exists. Distinguish undefined from a deliberately absent null.','const prices = [10, 20, 30];\nlet total = 0;\nfor (const price of prices) total += price;\nconsole.log(total);','a budget calculation with explicit numeric conversion and invalid-input handling.'),
('Functions, arrays, and objects','Functions can receive other functions. Array methods express transformations; avoid mutating shared input when a calculation can return a new value. Object spread copies only one level, so nested objects may still be shared.','const expenses = [{category:"books", amount:20}, {category:"travel", amount:10}];\nconst total = expenses.reduce((sum, item) => sum + item.amount, 0);','a category report without mutating the original expense array.'),
('DOM, events, and forms','The DOM is a mutable document tree. Respond to user events, validate input, then render from your data model. Use textContent for user text; inserting untrusted HTML creates an injection boundary.','const button = document.querySelector("button");\nbutton.addEventListener("click", () => { document.querySelector("output").textContent = "Saved locally"; });','an accessible task form that rejects blank input and renders text safely.'),
('Promises and the event loop','Promises represent eventual results. await pauses the async function, not the whole browser. Handle rejection and stale responses; the last request started may not be the last one completed.','async function load(read) { try { return await read(); } catch { return []; } }\nload(() => Promise.resolve(["Algorithms"])).then(console.log);','a simulated asynchronous search that discards outdated results.'),
('Modules and browser storage','Modules define explicit dependencies. Browser storage is local but can be cleared or unavailable. JSON decoding needs schema checks; store a version and offer an export before changing a format.','const snapshot = {version:1, tasks:[{id:1, title:"Study"}]};\nlocalStorage.setItem("tasks", JSON.stringify(snapshot));','a versioned task store that handles malformed JSON without replacing good data.'),
('Testing and maintainable design','Keep domain functions independent of the DOM so edge cases are easy to test. Test events and storage separately through adapters. A passing sample is insufficient: include empty input, duplicates, and failures.','function add(a, b) { if (!Number.isFinite(a) || !Number.isFinite(b)) throw new Error("finite numbers required"); return a+b; }\nconsole.assert(add(2,3) === 5);','a tested task app with a storage adapter and reproducible local instructions.')],[
('AFN expense calculator','Summarize daily expenses in the browser.',['Validate finite nonnegative amounts.','Render categories using safe text APIs.','Provide keyboard-accessible controls.']),
('Study task board','Organize local learning tasks.',['Create, edit, filter, and complete tasks with stable IDs.','Persist a versioned snapshot and handle corrupted data.','Export and import a validated JSON backup.']),
('Local quiz studio','Author and take quizzes without a service.',['Separate question data, scoring, and rendering.','Support keyboard interaction and accessible feedback.','Test scoring boundaries, persistence, and malformed imports.'])])

course('reactjs','ReactJs','javascript','Provision Node.js and a React project with pinned dependencies and a populated package cache. Use local development/build scripts from that project. All data, fonts, and images must be local; do not depend on a CDN.',[
('Components, JSX, and props','Components describe reusable UI. Props are inputs owned by a parent; do not mutate them. Break a design into components by responsibility and identify the minimum data required for each one.','function CourseCard({title}) { return <article><h2>{title}</h2></article>; }','a component tree for a course catalog with explicit props.'),
('State, events, and controlled inputs','State drives rendering. Use a state update function when the next value depends on the previous one. Controlled inputs keep the current value in state; validate without losing what the user typed.','function Counter() { const [count,setCount] = useState(0); return <button onClick={() => setCount(c => c+1)}>{count}</button>; }\n// import {useState} from "react";','a controlled expense form with validation and a derived total.'),
('Lists, keys, and reducers','Keys preserve identity between renders; array positions are unstable when rows move. A reducer centralizes state transitions and can reject invalid actions. Derived values usually do not need separate state.','function reducer(state, action) { if(action.type === "add") return [...state, action.item]; return state; }','a task reducer and test add, edit, delete, and duplicate-ID actions.'),
('Effects and external systems','Effects synchronize with systems outside rendering, such as storage or subscriptions. Clean up subscriptions and avoid using effects for values that can be calculated during render. Treat asynchronous completion after unmount as a lifecycle concern.','useEffect(() => { const handler = () => setOnline(navigator.onLine); window.addEventListener("online",handler); return () => window.removeEventListener("online",handler); }, []);','a storage adapter and explain which updates require an effect and which are derived.'),
('Composition, accessibility, and tests','Composition often avoids a large configuration-heavy component. Test behavior through labels and roles. Keep focus predictable when dialogs open and close, and test forms with a keyboard instead of only a mouse.','function Field({label, id, children}) { return <div><label htmlFor={id}>{label}</label>{children}</div>; }','an accessible edit dialog with focus restoration and behavior tests.'),
('Architecture and offline builds','Separate components, domain rules, and persistence adapters. A production build must bundle assets locally. Test the built artifact through a local server with internet disconnected; cached development assets can hide missing dependencies.','src/\n  features/tasks/\n  domain/taskReducer.js\n  adapters/localStore.js\n  components/Field.jsx','a production build with local data, failure states, and an architecture decision record.')],[
('Course catalog UI','Help students browse a local course list.',['Filter by topic without modifying source data.','Use stable keys and accessible controls.','Show an intentional no-results state.']),
('Attendance dashboard','Record attendance for a fictional class.',['Use reducer-driven updates and stable student IDs.','Persist local snapshots and compute derived percentages.','Test toggling, empty classes, and storage failures.']),
('Learning portfolio dashboard','Display projects and student reflections locally.',['Separate domain rules, UI, and storage.','Provide accessible editing and validated backup import.','Build a local production bundle and test with internet disconnected.'])])

course('reactnative','ReactNative','reactjs','Provision Node.js, a native React Native project, native SDKs, and all packages. Android uses Android Studio/JDK; iOS requires macOS/Xcode. Do not require an online Expo service or cloud build. Local native builds need their complete dependency cache.',[
('Native components and layout','React Native renders native platform components rather than browser DOM elements. Use View and Text, learn Flexbox defaults, and account for safe areas and different screen sizes.','import {View, Text} from "react-native";\nfunction Greeting() { return <View style={{padding:24}}><Text>Salam</Text></View>; }','a native information card that adapts to small and large screens.'),
('Input, state, and lists','TextInput emits text changes and FlatList renders large collections efficiently. Stable keys preserve item identity. Keep domain data separate from presentation and avoid nesting large scrolling lists unnecessarily.','<FlatList data={items} keyExtractor={item => item.id} renderItem={({item}) => <Text>{item.title}</Text>} />','a searchable list with controlled input and a meaningful empty state.'),
('Navigation and lifecycle','A screen may remain mounted when it loses focus. Distinguish component lifecycle from navigation focus. Pass stable IDs to detail screens and preserve appropriate form drafts when moving between screens.','// Navigation contract: Catalog -> Detail({itemId}) -> Edit({itemId}).\n// The repository owns records; route parameters carry IDs only.','a three-screen flow with predictable back behavior and draft preservation.'),
('Local storage and repository adapters','React Native does not provide browser localStorage. Choose a provisioned native storage adapter and validate serialized data. Expose async repository operations and show failures without discarding user edits.','async function saveItem(store, item) { if(!item.title.trim()) throw new Error("Title required"); await store.save(item); }','a replaceable local store with save-failure and restart tests.'),
('Platform APIs and accessibility','Permissions depend on the feature and platform. Ask in context and support denial. Accessibility labels, roles, and scalable text need native testing; a web accessibility result does not prove a native screen works.','<Pressable accessibilityRole="button" accessibilityLabel="Save note" onPress={save}><Text>Save</Text></Pressable>','an accessible export action that handles unavailable platform support.'),
('Testing and native packaging','Test pure rules in JavaScript and critical flows on a device or simulator. Native dependencies can behave differently across platforms. Produce a local build, record its platform, and verify the installed app without internet.','// Test matrix: Android/iOS, small/large text, empty/populated store, save failure, relaunch.','a native release candidate with documented platform gaps and reproducible offline build prerequisites.')],[
('Campus directory','Browse fictional campus contacts and places.',['Bundle records and local imagery.','Provide accessible search and detail views.','Handle narrow screens and larger text.']),
('Personal study tracker','Record study sessions on one device.',['Validate durations and preserve local records.','Summarize by subject without duplicate counting.','Test relaunch and storage failure.']),
('Field survey notebook','Collect fictional community survey records locally.',['Separate form validation and native storage.','Provide edit, export, and permission-denial behavior.','Verify a locally built native app in airplane mode.'])])

course('nodejs','NodeJs','javascript','Provision a Node.js runtime. The examples and initial projects use built-in modules; run node filename.mjs and node --test. Bind demonstration services to 127.0.0.1. No external network calls are required.',[
('Runtime and modules','Node.js runs JavaScript outside the browser and provides platform APIs. ES modules define imports and exports. Use explicit file extensions for local module paths and separate CLI input from domain logic.','import {parseArgs} from "node:util";\nconst {positionals} = parseArgs({allowPositionals:true});\nconsole.log(positionals);','a CLI that validates arguments and prints a useful usage message.'),
('Async filesystem operations','Promise-based IO avoids blocking while waiting, but CPU-heavy loops still block the event loop. Resolve file paths deliberately and handle missing or malformed data with specific errors.','import {readFile} from "node:fs/promises";\nconst text = await readFile("records.json", "utf8");\nconst records = JSON.parse(text);','a local report generator with missing-file and invalid-JSON cases.'),
('Streams and backpressure','Streams process chunks instead of loading entire files. Backpressure prevents a producer from overwhelming a consumer. pipeline connects error handling and completion across a chain; always handle its rejection.','import {pipeline} from "node:stream/promises";\nimport {createReadStream, createWriteStream} from "node:fs";\nawait pipeline(createReadStream("input.txt"), createWriteStream("copy.txt"));','a bounded-memory file copy with error handling and byte-for-byte verification.'),
('HTTP and event-loop behavior','An HTTP handler must finish each response. Validate route, method, and body size; a slow CPU task delays other requests. Listen on loopback for local exercises and close the server cleanly after tests.','import {createServer} from "node:http";\ncreateServer((req,res) => { res.writeHead(200,{"Content-Type":"application/json"}); res.end(JSON.stringify({status:"ok"})); }).listen(3000,"127.0.0.1");','a local health endpoint and measure how a CPU-heavy handler affects latency.'),
('Testing, workers, and contracts','Use node:test for deterministic domain checks. Workers can isolate CPU-heavy work, but messages must be bounded and lifecycle cleanup matters. Inject filesystem and clock dependencies when tests need controlled failures.','import test from "node:test";\nimport assert from "node:assert/strict";\ntest("empty total", () => assert.equal([].reduce((a,b)=>a+b,0),0));','a report worker with timeout handling and tests for malformed requests.'),
('Packaging and operational recovery','Document runtime requirements and command-line contracts. Avoid logging sensitive records. Atomic file replacement and explicit backup restoration reduce data-loss risk; a clean shutdown must finish or reject in-flight work predictably.','app/\n  cli.mjs\n  domain/report.mjs\n  adapters/files.mjs\n  test/report.test.mjs','a standard-library-only release with bounded inputs, local backup, and failure recovery tests.')],[
('CSV report CLI','Summarize fictional attendance data.',['Validate the documented CSV dialect and record schema.','Report malformed rows with line numbers.','Write deterministic summaries and test empty files.']),
('Local file catalog','Index a selected exercise directory.',['Restrict traversal to the chosen root and handle unreadable files.','Process large files without loading them all into memory.','Export a catalog and test interrupted operations.']),
('Offline reporting service','Serve local reports from fictional datasets.',['Bind to loopback and limit request and file sizes.','Separate HTTP, report rules, and persistence.','Test timeouts, invalid input, graceful shutdown, and backup recovery.'])])

course('expressjs','ExpressJs','nodejs','Provision Node.js and a pinned Express installation plus any testing dependencies. Use a local package cache and a lockfile. Bind to loopback and use fictional data; no cloud database or hosted API is required.',[
('Routing and middleware order','Express matches requests through an ordered middleware chain. A handler must respond or delegate. Put general parsing before routes and error handling after routes; middleware order changes behavior.','import express from "express";\nconst app = express();\napp.use(express.json({limit:"16kb"}));\napp.get("/health", (req,res) => res.json({status:"ok"}));\napp.listen(3000,"127.0.0.1");','a loopback service with health, not-found, and JSON routes.'),
('Validation and REST contracts','Validate types and business constraints at the boundary. Use status codes consistently and return structured errors without stack traces. An ID in the URL does not prove a caller may modify that resource.','app.post("/items", (req,res) => { if(typeof req.body?.name !== "string" || !req.body.name.trim()) return res.status(400).json({error:"name_required"}); res.status(201).json({name:req.body.name.trim()}); });','a create-item contract with missing, malformed, and valid request tests.'),
('Service and repository layers','Routes translate HTTP; services enforce rules; repositories persist state. Dependency injection allows an in-memory repository in tests. Avoid storing business policy in middleware that unrelated routes accidentally inherit.','function createItemService(repository) { return { list: () => repository.list() }; }','a replaceable item repository and keep domain tests independent of Express.'),
('Errors, authorization, and input limits','Handle known errors explicitly and hide internal details. Enforce authorization for each operation and bound request sizes. Offline operation does not make local input trustworthy. Authentication design needs vetted libraries and separate security review before real deployment.','app.use((error,req,res,next) => { if(res.headersSent) return next(error); res.status(500).json({error:"internal_error"}); });','a fictional-role authorization matrix and tests for denied operations and oversized requests.'),
('Integration tests and transactions','Exercise the service through HTTP with a temporary store. Assert response and resulting state, including failures. Related persistence operations must commit together; retries need a stable operation identifier to avoid duplicate writes.','// Test: POST loan -> 201; repeat operation ID -> same result;\n// conflicting loan -> 409; storage failure -> no partial loan.','an integration suite for atomic lending and idempotent retries.'),
('Local release and observability','Separate app construction from listen so tests can own ports and cleanup. Log operation IDs and outcomes without dumping personal data. Document runtime, dependency cache, fixtures, and restoration procedures for a disconnected machine.','export function createApp(service) { const app = express(); app.get("/items", async (req,res,next) => { try { res.json(await service.list()); } catch(error) { next(error); } }); return app; }','a release package with controlled startup, shutdown, and an offline smoke test.')],[
('Course catalog API','Expose a fictional training catalog locally.',['Implement list, detail, and filtered search routes.','Return consistent validation and not-found errors.','Test contracts through HTTP on a temporary port.']),
('Library lending API','Enforce loan rules behind HTTP endpoints.',['Use service and repository boundaries.','Prevent duplicate active loans and validate IDs.','Test rollback and idempotent retry behavior.']),
('Training enrollment service','Manage local enrollments for fictional courses.',['Enforce capacity and explicit role policies.','Bound requests and avoid leaking internal errors.','Ship integration tests, seed data, and offline operation instructions.'])])

course('flutter-dart','Flutter and Dart','', 'Provision Flutter/Dart, target SDKs, fonts, and all pub/native dependency caches. Use flutter pub get --offline after provisioning. Android and Windows need their native build tools; iOS builds require macOS/Xcode. The app’s Python sandbox does not execute Dart.',[
('Dart types and asynchronous code','Sound null safety makes absent values explicit. Futures represent eventual results and streams represent multiple events. Validate inputs at boundaries and keep calculation functions independent of widgets.','int total(List<int> values) => values.fold(0, (sum, value) => sum + value);\nvoid main() { assert(total([]) == 0); print(total([10,20])); }','a typed expense model and pure validation functions with boundary tests.'),
('Widgets, constraints, and layout','Flutter layout passes constraints down, sizes up, and positions children. A widget describes configuration; state belongs to an appropriate owner. Avoid unbounded flex children in scrolling layouts and test long labels.','class Greeting extends StatelessWidget { const Greeting({super.key}); @override Widget build(BuildContext context) => const Padding(padding: EdgeInsets.all(24), child: Text("Salam")); }','a responsive course card that supports narrow screens and larger text.'),
('State, navigation, and forms','Choose one owner for shared state and expose explicit actions. Navigation should carry stable IDs. Validate before saving and show progress while work is pending; only display success after persistence succeeds.','final formKey = GlobalKey<FormState>();\n// Form(key: formKey, child: TextFormField(validator: (v) => v == null || v.trim().isEmpty ? "Required" : null));','a list-detail-edit flow with validation and preserved input after a failed save.'),
('Clean architecture and local storage','Domain rules depend on contracts, and adapters implement SQLite or file storage. Inject repositories into application services. Transactions protect related writes; migrations and validated backup formats protect data across releases.','abstract interface class NoteRepository { Future<List<String>> load(); Future<void> save(List<String> notes); }\nclass LoadNotes { LoadNotes(this.repository); final NoteRepository repository; Future<List<String>> call() => repository.load(); }','a local repository with memory and persistent adapters plus migration fixtures.'),
('Isolates, accessibility, and testing','An isolate has separate memory and communicates with messages. Bound work and terminate a worker on timeout. Unit tests check rules, widget tests check interaction, and integration tests check real plugins and startup.','final result = await Isolate.run(() => [1,2,3].fold(0, (a,b) => a+b));\n// Import dart:isolate; use explicit worker lifecycle control for cancellable work.','a bounded report worker and accessible UI tests with large text and storage failures.'),
('Release engineering and offline guarantees','A release must include assets and native libraries for its target. Separate developer provisioning from learner runtime. Verify first launch, learning, saving, restart, and backup with internet disabled; keep signing secrets out of source control.','lib/\n  domain/\n  application/\n  data/\n  presentation/\n  runtime/\ntest/\nintegration_test/','an offline release candidate with dependency documentation, CI checks, and real-device acceptance evidence.')],[
('Student timetable','Build a responsive local timetable.',['Use typed data and accessible day navigation.','Bundle content and fonts.','Test narrow layout and large text.']),
('Offline expense journal','Record fictional expenses across app restarts.',['Inject a local repository and validate amounts.','Persist atomically and implement validated JSON backup.','Test failed saves and backup round trips.']),
('Mini learning platform','Create a small offline education app using the architecture taught here.',['Separate curriculum, assessment, portfolio, storage, and UI responsibilities.','Bundle lessons and track progress without accounts or network calls.','Deliver unit, widget, integration tests and a verified target-specific release.'])])

for c in courses:
    c['beginner'] = GUIDES[c['id']]
payload = json.dumps(courses, ensure_ascii=False, separators=(',', ':'))
target = ROOT / 'lib/data/bundled_curriculum.dart'
target.write_text("// Generated by tool/build_curriculum.py; edit the authoring source.\nimport 'dart:convert';\nimport '../domain/curriculum.dart';\nclass BundledCurriculum implements CurriculumRepository {\n const BundledCurriculum();\n static final List<StudyCourse> _catalog = List.unmodifiable((jsonDecode(_source) as List).map((e) => StudyCourse(e as Map<String,dynamic>)));\n @override List<StudyCourse> get catalog => _catalog;\n}\nconst _source = r'''" + payload + "''';\n", encoding='utf-8')
(ROOT/'assets/curriculum').mkdir(parents=True,exist_ok=True)
(ROOT/'assets/curriculum/catalog.json').write_text(json.dumps(courses,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
lines = ['# Learn By Marifat Team — Curriculum and lesson plans', '', 'Original curriculum, edition 1. Bloom means the revised cognitive taxonomy, not an accreditation or a fixed rule requiring every lesson to traverse six levels. These are guided lesson plans and project assignments, not a claim that all topics have full interactive textbooks or embedded compilers.', '', 'Every course has six modules, twelve planned sessions (15 guided hours), and three projects (6 + 12 + 24 estimated hours). Allow additional practice and remediation. “Zero to Hero” names the Python pathway; competence requires demonstrated work, not seat time.', '', '## Lesson delivery protocol', '', 'Guided session (60 min): retrieval 5, explanation and worked trace 15, guided practice 20, evidence assessment 15, reflection 5. Independent studio (90 min): retrieval 10, design 15, implementation 35, testing/review 20, reflection 10. Read the module explanation and example before the activity. Examples marked as fragments belong inside a provisioned project; they are not all standalone programs.', '', 'Remediation: return to the worked trace, reduce the input to one record, explain the failure, then retry with a different input. Extension: add a justified requirement and regression tests. Pair work is optional; a paper trace and self-review provide an offline alternative. Plans, evidence prompts, and examples are bundled in the app; toolchains are separately provisioned.', '', '## Project assessment rubric', '', 'Score each dimension from 0 to 3: correctness, design, verification, usability/accessibility, and reproducibility. 0 = absent; 1 = partial with major gaps; 2 = meets requirements with recorded evidence; 3 = meets requirements plus justified edge-case improvements. Recommended readiness: every requirement demonstrated and every dimension at least 2. Self-ratings are provisional until a peer or teacher reviews the evidence. No automatic certification.', '']
for c in courses:
    lines += [f"## {c['title']}", '', 'Prerequisites: '+(', '.join(c['prerequisites']) or 'No prior programming required; basic device and file use.'), '', 'Offline tools: '+c['tools'], '']
    g=c['beginner']
    lines += ['### Start here: first guided lesson','',g['before'],'','Vocabulary:','']+['- '+t for t in g['terms']]+['','```text',g['code'],'```','']+['- '+t for t in g['trace']]+['','Readiness check: '+g['question'],'','Answer: '+g['options'][g['answer']],'','Guided practice: '+g['task'],'','Hint: '+g['hint'],'','Reference solution:','','```text',g['solution'],'```','','Expected result: '+g['result'],'']
    for m in c['modules']:
        lines += [f"### {m['title']}", '', m['explanation'], '', '```text',m['example'],'```','']
        for p in m['plans']:
            lines += [f"#### {p['title']} ({p['minutes']} min; {p['level'].title()})",'',f"ID: `{p['id']}`",'', 'Objective: '+p['objective'],'','Activity: '+p['activity'],'','Assessment evidence: '+p['evidence'],'']
    for p in c['projects']:
        lines += [f"### Project: {p['title']} ({p['hours']} hours)",'',p['brief'],'','Acceptance conditions:','']+['- '+r for r in p['requirements']]+['','Milestones:','']+['- '+m for m in p['milestones']]+['']
(ROOT/'docs/CURRICULUM.md').write_text('\n'.join(lines),encoding='utf-8')
print(f'Generated {len(courses)} courses, {sum(len(c["modules"])*2 for c in courses)} lesson plans, {sum(len(c["projects"]) for c in courses)} projects.')
