"""Five offline database pathways; authored text, fixtures and translations."""
TEXT = {}
COURSES = []
def t(en, fa, ps):
    TEXT[en] = {'fa': fa, 'ps': ps}
    return en

LOCAL = t('Use the in-app SQL practice for read-only queries on fictional data. The worked scripts can also be run in a separately prepared SQLite tool. Each example starts with a fresh database; no internet or account is needed.', 'برای پرس‌وجوی خواندنی روی معلومات فرضی از تمرین SQL داخل برنامه استفاده کنید. دستورهای کامل در ابزار آمادهٔ SQLite نیز اجرا می‌شوند. هر مثال دیتابیس تازه دارد؛ اینترنت و حساب لازم نیست.', 'د فرضي معلوماتو د لوستلو پوښتنو لپاره د اپ دننه SQL تمرین وکاروئ. بشپړ سکریپټونه په چمتو SQLite وسیله کې هم چلېږي. هر مثال نوی ډیټابېس لري؛ انټرنېټ او حساب نه غواړي.')
PG = t('Lessons and practice traces are bundled offline. Executing PostgreSQL-specific scripts requires a separately installed local PostgreSQL server and psql. Use a disposable training database and a restricted local user. The in-app SQL practice runs SQLite, not PostgreSQL.', 'درسونه او د تمرین تشریح آفلاین دي. د PostgreSQL ځانګړي سکریپټونه جلا نصب شوی محلي سرور او psql غواړي. موقتي تمریني ډیټابېس او محدود محلي کارن وکاروئ. د اپ SQL تمرین SQLite چلوي، PostgreSQL نه.', 'درس‌ها و شرح تمرین‌ها آفلاین اند. اجرای دستورهای ویژهٔ PostgreSQL سرور محلی نصب‌شده و psql لازم دارد. دیتابیس موقت تمرینی و کاربر محلی محدود استفاده کنید. تمرین SQL برنامه SQLite است، نه PostgreSQL.')
TEXT[PG]['fa'], TEXT[PG]['ps'] = TEXT[PG]['ps'], TEXT[PG]['fa']
MONGO = t('Lessons and document traces work offline. Executing these commands requires a separately provisioned local MongoDB server and mongosh. No Atlas account or cloud service is required. Use a disposable training database; the in-app SQLite editor cannot execute MongoDB commands.', 'درس‌ها و شرح سندها آفلاین اند. اجرای دستورها سرور محلی MongoDB و mongosh آماده می‌خواهد. حساب Atlas و خدمت ابری لازم نیست. دیتابیس موقت تمرینی استفاده کنید؛ ویرایشگر SQLite برنامه دستور MongoDB اجرا نمی‌کند.', 'درسونه او د سندونو تشریح آفلاین دي. د قوماندو اجرا چمتو محلي MongoDB سرور او mongosh غواړي. Atlas حساب او ابري خدمت نه غواړي. موقتي تمریني ډیټابېس وکاروئ؛ د اپ SQLite سمونګر MongoDB نه چلوي.')

def module(title, explanation, code, trace, task):
    return {'title': title, 'explanation': explanation, 'code': code, 'trace': trace, 'task': task}

def project(title, brief, requirements):
    return (title, brief, requirements)

def c(id, title, prerequisites, tools, modules, projects):
    assert len(modules) == 6 and len(projects) == 3
    COURSES.append(dict(id=id,title=title,prerequisites=prerequisites,tools=tools,modules=modules,projects=projects))

BOOKS = "CREATE TABLE books(id INTEGER PRIMARY KEY, title TEXT NOT NULL, price INTEGER NOT NULL CHECK(price >= 0));\nINSERT INTO books VALUES (1,'Python',100),(2,'Databases',150),(3,'Web',100);\n"

c('database-foundations', t('Database Foundations', 'مبانی دیتابیس', 'د ډیټابېس بنسټونه'), '', LOCAL, [
module(t('Tables, rows, and columns','جدول، سطر و ستون','جدول، کتار او ستنه'),
t('A database organizes information so it can be found and checked. Imagine a library register: each book is one row, and title and price are columns. A table describes the fields every record uses. SQL is a language for asking the database to create, read, and change records. Keeping data in a table is different from displaying it on a screen.', 'دیتابیس معلومات را منظم می‌کند تا پیدا و بررسی شوند. ثبت کتابخانه را تصور کنید: هر کتاب یک سطر و عنوان و قیمت ستون‌ها اند. جدول فیلدهای هر ثبت را مشخص می‌کند. SQL زبان ساختن، خواندن و تغییر ثبت‌ها است. نگه‌داشتن معلومات در جدول با نمایش در صفحه فرق دارد.', 'ډیټابېس معلومات منظموي څو وموندل او وکتل شي. د کتابتون ثبت تصور کړئ: هر کتاب یو کتار او نوم او بیه ستنې دي. جدول د هر ثبت خانې ټاکي. SQL د ثبتونو جوړولو، لوستلو او بدلولو ژبه ده. په جدول کې ساتل په پرده له ښودلو سره توپیر لري.'),
BOOKS+'SELECT title, price FROM books ORDER BY id;',
t('CREATE TABLE defines the structure but adds no books. INSERT adds three rows. SELECT asks for two columns and ORDER BY id fixes the display order. The rows are Python/100, Databases/150, and Web/100. A result table is a view of stored data, not a second saved copy.', 'CREATE TABLE جوړښت ټاکي، کتابونه نه زیاتوي. INSERT درې کتارونه زیاتوي. SELECT دوه ستنې غواړي او ORDER BY id ترتیب ټاکي. پایلې Python/100، Databases/150 او Web/100 دي. د پایلې جدول د ساتل شوو معلوماتو لید دی، دویمه ساتل شوې کاپي نه ده.', 'CREATE TABLE ساختار می‌سازد و کتاب اضافه نمی‌کند. INSERT سه سطر اضافه می‌کند. SELECT دو ستون می‌خواهد و ORDER BY id ترتیب را تعیین می‌کند. نتیجه Python/100، Databases/150 و Web/100 است. جدول نتیجه نمای معلومات است، نه کاپی ذخیره‌شدهٔ دوم.'),
t('Read only the title column and keep the rows ordered by id.', 'فقط ستون عنوان را بخوانید و ترتیب id را نگه دارید.', 'یوازې د نوم ستنه ولولئ او د id ترتیب وساتئ.')),
module(t('Identity and primary keys','هویت و کلید اصلی','هویت او اصلي کلی'),
t('Two students may share a name, so a name is a poor identity. A primary key uniquely identifies a row. Other records can refer to that stable key even after a title changes. Choose identity independently of display order: the first visible row is not necessarily record 1.', 'دو شاگرد می‌توانند هم‌نام باشند؛ نام شناسهٔ مناسب نیست. کلید اصلی هر سطر را یکتا مشخص می‌کند. ثبت‌های دیگر حتی پس از تغییر عنوان به همان کلید اشاره می‌کنند. هویت را از ترتیب نمایش جدا کنید؛ اولین سطر دیده‌شده الزاماً ثبت 1 نیست.', 'دوه زده کوونکي یو نوم لرلای شي؛ نوم ښه پېژند نه دی. اصلي کلی هر کتار یکتا پېژني. نور ثبتونه د نوم له بدلون وروسته هم هماغه کلي ته اشاره کوي. هویت له ښودلو ترتیب جلا کړئ؛ لومړی لیدل شوی کتار تل ثبت 1 نه دی.'),
BOOKS+"UPDATE books SET title='Python basics' WHERE id=1;\nSELECT id,title FROM books ORDER BY id;",
t('The update changes the title of row 1 only. Its id stays 1, so references remain meaningful. Without WHERE, every title would change. In a fresh practice copy, try inserting another row with id 1 and expect a key constraint failure rather than two ambiguous identities.', 'تغییر فقط عنوان سطر 1 را عوض می‌کند و شناسه 1 می‌ماند. بدون WHERE تمام عنوان‌ها تغییر می‌کردند. در نسخهٔ تازهٔ تمرینی، ثبت دوم با id برابر 1 را امتحان کنید؛ باید خطای کلید بدهد، نه دو هویت مبهم.', 'بدلون یوازې د 1 کتار نوم بدلوي او پېژند 1 پاتې کېږي. بې WHERE ټول نومونه بدلېدل. په تازه تمریني کاپي کې دویم id=1 ثبت وازمویئ؛ باید د کلي خطا ورکړي، نه دوه مبهم هویتونه.'),
t('Rename book 2 without changing either its id or the other books.', 'نام کتاب 2 را بدون تغییر شناسه یا کتاب‌های دیگر عوض کنید.', 'د 2 کتاب نوم بدل کړئ، پېژند او نور کتابونه مه بدلوئ.')),
module(t('Relationships and foreign keys','رابطه‌ها و کلید خارجی','اړیکې او بهرنی کلی'),
t('A loan belongs to a book, so store the book id on the loan instead of copying all book fields. This is a relationship. A foreign key rejects references to missing books when enforcement is enabled. It does not automatically limit a book to one active loan; that is another rule.', 'امانت مربوط به کتاب است؛ شناسهٔ کتاب را در امانت نگه دارید، نه همهٔ مشخصات را کاپی کنید. این رابطه است. کلید خارجی با فعال بودن بررسی، اشاره به کتاب ناموجود را رد می‌کند. محدود کردن به یک امانت فعال قاعدهٔ دیگری است.', 'پور په کتاب پورې اړه لري؛ په پور کې د کتاب پېژند وساتئ، ټولې خانې مه کاپي کوئ. دا اړیکه ده. بهرنی کلی د فعالې کتنې پر مهال ورک کتاب ته اشاره ردوي. یوازې یو فعال پور اجازه کول بله قاعده ده.'),
'PRAGMA foreign_keys=ON;\n'+BOOKS+'CREATE TABLE loans(id INTEGER PRIMARY KEY, book_id INTEGER NOT NULL REFERENCES books(id));\nINSERT INTO loans VALUES(1,2);\nSELECT b.title FROM loans l JOIN books b ON b.id=l.book_id;',
t('Foreign key enforcement is enabled before writing. Loan 1 refers to book 2. The join follows that reference and returns Databases. An attempted book_id of 99 fails because no such parent row exists. Deleting a referenced book also requires an explicit relationship policy.', 'بررسی کلید خارجی پیش از نوشتن فعال است. امانت 1 به کتاب 2 اشاره می‌کند. join این رابطه را دنبال و Databases می‌دهد. book_id برابر 99 رد می‌شود، چون والد ندارد. حذف کتاب امانت‌شده هم به قاعدهٔ مشخص رابطه ضرورت دارد.', 'د بهرني کلي کتنه له لیکلو مخکې فعاله ده. پور 1 کتاب 2 ته اشاره کوي. join اړیکه تعقیبوي او Databases ورکوي. book_id=99 رد کېږي ځکه مورنی کتار نشته. د پور شوي کتاب ړنګول هم د اړیکې څرګنده قاعده غواړي.'),
t('Add a second loan for book 1 and list both referenced titles.', 'امانت دوم برای کتاب 1 اضافه و هر دو عنوان را فهرست کنید.', 'د کتاب 1 لپاره دویم پور زیات او دواړه نومونه وښيئ.')),
module(t('Reducing duplicate facts','کاهش معلومات تکراری','د تکراري حقایقو کمول'),
t('Repeating a category name on every book makes renaming error-prone. Put each category in its own row and reference its key. This is one step toward normalization: store one fact in one appropriate place. Separate tables when they represent independent facts, not merely because more tables look advanced.', 'تکرار نام کتگوری در هر کتاب تغییر نام را خطاپذیر می‌کند. هر کتگوری را جدا ثبت و به کلیدش اشاره کنید. این یک گام نرمال‌سازی است: هر واقعیت در جای مناسب خود باشد. جدول را برای واقعیت مستقل جدا کنید، نه فقط برای زیاد کردن جدول‌ها.', 'په هر کتاب کې د کتګورۍ نوم تکرارول د نوم بدلون تېروتنه زیاتوي. هره کتګوري جلا ثبت او کلي ته یې اشاره وکړئ. دا د نورمالولو یو ګام دی: هر حقیقت په مناسب ځای کې وساتئ. جدول د خپلواک حقیقت لپاره جلا کړئ، یوازې د شمېر زیاتولو لپاره نه.'),
"CREATE TABLE categories(id INTEGER PRIMARY KEY,name TEXT NOT NULL);\nCREATE TABLE titles(id INTEGER PRIMARY KEY,title TEXT,category_id INTEGER);\nINSERT INTO categories VALUES(1,'Computing');\nINSERT INTO titles VALUES(1,'Python',1),(2,'Web',1);\nSELECT title,name FROM titles JOIN categories ON categories.id=titles.category_id ORDER BY titles.id;",
t('Both books reference category 1, so one category name is stored. The join displays Computing twice because two books use it; repeated output is not duplicated storage. This minimal example omits the foreign key deliberately: add it before relying on referential integrity.', 'هر دو کتاب به کتگوری 1 اشاره دارند و نام آن یک بار ذخیره شده است. join دوبار Computing نشان می‌دهد چون دو کتاب از آن استفاده می‌کنند؛ تکرار نتیجه، تکرار ذخیره نیست. در این نمونه کلید خارجی حذف شده است؛ پیش از اعتماد به رابطه آن را اضافه کنید.', 'دواړه کتابونه کتګورۍ 1 ته اشاره لري او نوم یې یو ځل ساتل شوی. join دوه ځله Computing ښيي ځکه دوه کتابونه یې کاروي؛ تکراري پایله تکراري ساتنه نه ده. دې وړې نمونې بهرنی کلی نه دی ایښی؛ له باور مخکې یې ورزیات کړئ.'),
t('Rename the shared category once and explain why both result rows change.', 'کتگوری مشترک را یک بار تغییر و دلیل تغییر هر دو سطر نتیجه را توضیح بدهید.', 'ګډه کتګوري یو ځل بدله او د دواړو پایلو د بدلون دلیل ووایئ.')),
module(t('Constraints and valid records','محدودیت‌ها و ثبت معتبر','محدودیتونه او معتبر ثبتونه'),
t('Validation in a screen can be bypassed by another writer. Database constraints provide a second boundary. NOT NULL rejects missing values and CHECK enforces a stated condition. A non-null title can still be blank, so encode the actual rule rather than assuming the type says everything.', 'بررسی صفحه ممکن است توسط نویسندهٔ دیگر دور زده شود. محدودیت دیتابیس مرز دوم است. NOT NULL مقدار ناموجود و CHECK شرط مشخص را بررسی می‌کند. عنوان غیرnull هنوز می‌تواند خالی باشد؛ قاعدهٔ واقعی را بنویسید، نه آن‌که نوع را کافی بدانید.', 'د پردې کتنه بل لیکونکی تېرېدای شي. د ډیټابېس محدودیت دویمه پوله ده. NOT NULL ورک ارزښت ردوي او CHECK شرط ګوري. غیرnull نوم لا هم تش کېدای شي؛ واقعي قاعده ولیکئ، یوازې ډول بسنه نه کوي.'),
"CREATE TABLE students(id INTEGER PRIMARY KEY,name TEXT NOT NULL CHECK(length(trim(name))>0),age INTEGER NOT NULL CHECK(age>=0));\nINSERT INTO students VALUES(1,'Amina',20);\nSELECT name,age FROM students;",
t('The valid row returns Amina and 20. Try an empty name or age -1 in a disposable copy: the corresponding CHECK rejects it. Constraints protect this table, but deciding whether an age is plausible for a specific enrollment still requires a clear application policy.', 'سطر معتبر Amina و 20 می‌دهد. نام خالی یا سن -1 را در کاپی تمرینی امتحان کنید؛ CHECK مربوط رد می‌کند. محدودیت همین جدول را محافظت می‌کند؛ مناسب بودن سن برای ثبت‌نام مشخص هنوز قاعدهٔ روشن برنامه می‌خواهد.', 'معتبر کتار Amina او 20 ورکوي. تش نوم یا -1 عمر په تمریني کاپي کې وازمویئ؛ اړوند CHECK یې ردوي. محدودیت همدا جدول ساتي؛ د ځانګړي نوم‌لیکنې لپاره د عمر مناسبت لا څرګنده کاري قاعده غواړي.'),
t('Add a check that rejects a blank book title and test a spaces-only title.', 'بررسی رد عنوان خالی را اضافه و عنوان فقط فاصله را آزمایش کنید.', 'د تش کتاب نوم ردولو کتنه ورزیاته او یوازې تشې لرونکی نوم وازمویئ.')),
module(t('Transactions and recovery','معامله و بازیابی','معامله او راګرځول'),
t('Some changes must succeed together. A transaction groups them so a rollback can undo unfinished work. Think of transferring stock between shelves: subtracting without adding loses inventory. COMMIT accepts the changes; ROLLBACK cancels them. A backup is separate: it protects against loss beyond one unfinished transaction.', 'بعضی تغییرها باید یک‌جا موفق شوند. معامله آن‌ها را گروه می‌کند تا rollback کار ناتمام را لغو کند. انتقال موجودی میان دو الماری را تصور کنید؛ کم کردن بدون افزودن موجودی را گم می‌کند. COMMIT تأیید و ROLLBACK لغو می‌کند. پشتیبان محافظت جدا از معامله است.', 'ځینې بدلونونه باید یوځای بریالي شي. معامله یې ډله کوي څو rollback نیمګړی کار لغوه کړي. د دوو الماریو ترمنځ موجودي لېږد تصور کړئ؛ کمول بې زیاتولو موجودي ورکوي. COMMIT مني او ROLLBACK لغوه کوي. بیک اپ له معاملې جلا ساتنه ده.'),
BOOKS+'BEGIN;\nUPDATE books SET price=0 WHERE id=1;\nROLLBACK;\nSELECT price FROM books WHERE id=1;',
t('The transaction temporarily changes book 1 to zero. ROLLBACK cancels that change, so the final SELECT returns 100. Replacing ROLLBACK with COMMIT would keep zero. Test both on fresh copies; a successful rollback does not prove that a separate backup can be restored.', 'معامله قیمت کتاب 1 را موقت صفر می‌کند. ROLLBACK آن را لغو و SELECT نهایی 100 می‌دهد. با COMMIT صفر باقی می‌ماند. هر دو را در کاپی تازه آزمایش کنید؛ rollback موفق ثابت نمی‌کند پشتیبان جدا قابل بازگردانی است.', 'معامله د کتاب 1 بیه لنډمهاله صفر کوي. ROLLBACK یې لغوه کوي او وروستی SELECT سل ورکوي. په COMMIT صفر پاتې کېږي. دواړه په تازه کاپیو وازمویئ؛ بریالی rollback د جلا بیک اپ د راګرځولو ثبوت نه دی.'),
t('Compare committed and rolled-back price changes and record both final values.', 'تغییر تأییدشده و لغوشده را مقایسه و هر دو قیمت نهایی را ثبت کنید.', 'منل شوی او لغوه شوی بدلون پرتله او دواړه وروستۍ بیې ثبت کړئ.'))
], [
project(t('Library data model','مدل معلومات کتابخانه','د کتابتون معلوماتي ماډل'),t('Design books, members, and loans for a fictional community library.', 'کتاب، عضو و امانت را برای کتابخانهٔ فرضی طراحی کنید.', 'د فرضي کتابتون کتابونه، غړي او پورونه طرحه کړئ.'),[
t('Use stable keys and enforce references to existing books and members.','کلید ثابت و اشاره به کتاب و عضو موجود را تضمین کنید.','ثابت کلي او موجودو کتابونو او غړو ته اشارې تضمین کړئ.'),t('Demonstrate valid loans and rejected missing references.','امانت معتبر و رد اشارهٔ ناموجود را نشان بدهید.','معتبر پور او د ورکې اشارې رد وښيئ.'),t('Explain how returned loans remain as history.','باقی ماندن سابقهٔ امانت برگشتی را توضیح بدهید.','د بېرته ورکړل شوي پور د تاریخ پاتې کېدل تشریح کړئ.')]),
project(t('Training enrollment model','مدل ثبت‌نام آموزشی','د روزنې نوم‌لیکنې ماډل'),t('Model students attending several courses without duplicating student details.','حضور شاگرد در چند کورس را بدون تکرار مشخصات طراحی کنید.','په څو کورسونو کې زده کوونکي بې تکراري مشخصاتو طرحه کړئ.'),[t('Separate students, courses, and enrollments.','شاگرد، کورس و ثبت‌نام را جدا کنید.','زده کوونکي، کورسونه او نوم‌لیکنې جلا کړئ.'),t('Prevent the same student enrolling twice in the same course.','ثبت تکراری شاگرد در همان کورس را منع کنید.','په هماغه کورس کې تکراري نوم‌لیکنه منع کړئ.'),t('Test renaming a course without breaking its enrollments.','تغییر نام کورس بدون خرابی ثبت‌نام را آزمایش کنید.','د کورس نوم بدلول بې نوم‌لیکنې خرابېدو وازمویئ.')]),
project(t('Shop stock transfer','انتقال موجودی دکان','د دوکان موجودي لېږد'),t('Model stock transfers between two fictional shelves with no lost units.','انتقال موجودی میان دو الماری فرضی را بدون گم‌شدن واحد طراحی کنید.','د دوو فرضي الماریو ترمنځ موجودي بې ورکو واحدونو طرحه کړئ.'),[t('Reject negative stock and invalid shelf references.','موجودی منفی و الماری نامعتبر را رد کنید.','منفي موجودي او ناسمې المارۍ رد کړئ.'),t('Group subtraction and addition in one transaction.','کم‌کردن و افزودن را در یک معامله انجام دهید.','کمول او زیاتول په یوه معامله کې وکړئ.'),t('Force a failure and prove both shelf quantities remain unchanged.','ناکامی ایجاد و ثابت کنید مقدار هر دو الماری ثابت مانده است.','ناکامي جوړه او د دواړو الماریو د مقدار پاتې کېدل ثابت کړئ.')])])

# All relational examples are self-contained SQLite scripts, with explicit order.
def sqlmod(title, desc, suffix, trace, task): return module(title,desc,BOOKS+suffix,trace,task)
c('sql', t('SQL from Zero','SQL از صفر','SQL له صفره'), 'database-foundations', LOCAL, [
sqlmod(t('SELECT and column names','SELECT و نام ستون','SELECT او د ستنو نومونه'),t('SELECT describes the columns you want; FROM names their table. Start with one table before joining several. Selecting columns does not modify stored rows. ORDER BY makes result order explicit; without it, do not rely on whichever order the database happens to return.', 'SELECT ستون‌های خواسته‌شده و FROM جدول را مشخص می‌کند. پیش از وصل چند جدول از یک جدول شروع کنید. انتخاب ستون معلومات را تغییر نمی‌دهد. ORDER BY ترتیب صریح می‌دهد؛ بدون آن به ترتیب اتفاقی اعتماد نکنید.', 'SELECT غوښتل شوې ستنې او FROM جدول ټاکي. له څو جدولونو نښلولو مخکې له یوه پیل کړئ. ستنې ټاکل معلومات نه بدلوي. ORDER BY څرګند ترتیب ورکوي؛ بې له هغه پر تصادفي ترتیب باور مه کوئ.'),'SELECT title AS book_name FROM books ORDER BY id;',t('The alias book_name labels the result column without renaming the stored title field. Three titles appear in id order. SELECT * would request every column, making the output contract depend on later schema changes. Prefer the fields your caller actually uses.','book_name نام ستون نتیجه است و فیلد title را در ذخیره تغییر نمی‌دهد. سه عنوان به ترتیب id دیده می‌شوند. SELECT * همهٔ ستون‌ها را می‌خواهد و قرارداد نتیجه را به تغییر ساختار وابسته می‌کند. فقط فیلد لازم را بخواهید.','book_name د پایلې ستنې نوم دی او ساتل شوی title نه بدلوي. درې نومونه په id ترتیب ښکاري. SELECT * ټولې ستنې غواړي او پایله د جوړښت له بدلون سره تړي. یوازې اړینې خانې وغواړئ.'),t('Return id and title with clear result column names.','شناسه و عنوان را با نام روشن ستون نتیجه برگردانید.','پېژند او نوم له څرګندو پایله نومونو سره ورکړئ.')),
sqlmod(t('Filtering and ordering','فلتر و ترتیب','چاڼ او ترتیب'),t('WHERE keeps rows whose condition is true. Compare prices as numbers, not text. ORDER BY can sort the filtered rows, and LIMIT can bound a preview. Filtering happens before the final limit, so a preview should state both its condition and its ordering.', 'WHERE سطرهایی را نگه می‌دارد که شرط‌شان درست است. قیمت را عددی مقایسه کنید، نه متن. ORDER BY نتیجه را مرتب و LIMIT پیش‌نمایش را محدود می‌کند. فلتر پیش از محدودیت نهایی است؛ شرط و ترتیب پیش‌نمایش را روشن کنید.', 'WHERE هغه کتارونه ساتي چې شرط یې رښتیا وي. بیې د عدد په توګه پرتله کړئ، نه متن. ORDER BY مرتبوي او LIMIT مخکتنه محدودوي. چاڼ له وروستي حد مخکې دی؛ د مخکتنې شرط او ترتیب څرګند کړئ.'),'SELECT title,price FROM books WHERE price>=100 ORDER BY price DESC,id LIMIT 2;',t('All three rows meet the condition. Descending price puts Databases first at 150. The two 100-price books tie, so id breaks the tie; Python is second. LIMIT returns those two rows. Without a tie-breaker, a tied preview may be unstable.','هر سه سطر شرط را دارند. ترتیب نزولی Databases را با 150 اول می‌آورد. دو قیمت 100 مساوی اند؛ id تساوی را می‌شکند و Python دوم است. LIMIT دو سطر می‌دهد. بدون قاعدهٔ تساوی ترتیب ثابت نیست.','درې واړه شرط پوره کوي. نزولي بیه Databases په 150 لومړی راولي. دوه 100 بیې برابرې دي؛ id توپیر ټاکي او Python دویم دی. LIMIT دوه کتارونه ورکوي. بې برابرۍ ماتولو ترتیب ثابت نه دی.'),t('List books costing exactly 100, ordered by title.','کتاب‌های دقیقاً 100 را به ترتیب عنوان فهرست کنید.','د پوره 100 بیې کتابونه د نوم په ترتیب وښيئ.')),
sqlmod(t('Totals and grouping','مجموع و گروه‌بندی','مجموعه او ډله کول'),t('COUNT counts records and SUM adds numeric values. GROUP BY computes a result for each group rather than one grand total. WHERE filters individual rows before grouping; HAVING filters groups after aggregation. Decide which question you are asking before choosing either filter.', 'COUNT ثبت‌ها را می‌شمارد و SUM مقدارهای عددی را جمع می‌کند. GROUP BY برای هر گروه نتیجه می‌سازد، نه یک مجموع عمومی. WHERE پیش از گروه‌بندی سطر و HAVING پس از آن گروه را فلتر می‌کند. نخست پرسش خود را مشخص کنید.', 'COUNT ثبتونه شمېري او SUM عددي ارزښتونه جمع کوي. GROUP BY د هرې ډلې لپاره پایله جوړوي، نه یوه عمومي مجموعه. WHERE له ډلې مخکې کتار او HAVING وروسته ډله چاڼوي. لومړی خپله پوښتنه وټاکئ.'),'SELECT price,COUNT(*) AS copies FROM books GROUP BY price ORDER BY price;',t('There are two price groups. Price 100 has two rows and price 150 has one. COUNT(*) counts rows, not the numeric sum of prices. SUM(price) across the original table is 350. An empty input makes SUM return NULL, so choose an explicit empty-total policy.','دو گروه قیمت داریم: 100 دو سطر و 150 یک سطر دارد. COUNT(*) تعداد سطر را می‌دهد، نه مجموع قیمت. SUM(price) در جدول اصلی 350 است. ورودی خالی برای SUM مقدار NULL می‌دهد؛ قاعدهٔ مجموع خالی را روشن کنید.','دوه بیه ډلې دي: 100 دوه کتارونه او 150 یو لري. COUNT(*) کتارونه شمېري، بیې نه جمع کوي. په اصلي جدول SUM(price) د 350 ارزښت دی. تشه داخله SUM ته NULL ورکوي؛ د تشې مجموعې قاعده څرګنده کړئ.'),t('Calculate total price and explain the difference from the book count.','مجموع قیمت را حساب و تفاوتش با تعداد کتاب را توضیح بدهید.','ټوله بیه حساب او د کتابونو له شمېر سره یې توپیر ووایئ.')),
sqlmod(t('Joining related tables','وصل جدول‌های مرتبط','اړوند جدولونه نښلول'),t('A join combines rows according to a relationship. INNER JOIN keeps matching pairs; LEFT JOIN also keeps left-side rows without a match. A book with two loans can produce two result rows. That is expected relationship behavior, not automatically a duplicate-data bug.', 'join سطرها را بر اساس رابطه وصل می‌کند. INNER JOIN جفت مطابق و LEFT JOIN سطر چپ بدون مطابق را هم نگه می‌دارد. کتاب با دو امانت می‌تواند دو سطر نتیجه بسازد. این رفتار رابطه است و الزاماً خطای تکرار نیست.', 'join کتارونه د اړیکې له مخې نښلوي. INNER JOIN برابرې جوړې او LEFT JOIN بې جوړې کیڼ کتارونه هم ساتي. د دوو پورونو کتاب دوه پایلې ورکولای شي. دا د اړیکې چلند دی، حتمي تکراري خطا نه ده.'),'CREATE TABLE loans(id INTEGER PRIMARY KEY,book_id INTEGER);\nINSERT INTO loans VALUES(1,1),(2,1);\nSELECT b.title,COUNT(l.id) AS loans FROM books b LEFT JOIN loans l ON l.book_id=b.id GROUP BY b.id,b.title ORDER BY b.id;',t('Python matches two loans; the other books match none. COUNT(l.id) ignores the NULL placeholder from unmatched rows, producing 2, 0, 0. COUNT(*) would count each retained left row and incorrectly suggest one loan for an unloaned book. Choose the counted expression deliberately.','Python دو امانت دارد و دیگر کتاب‌ها ندارند. COUNT(l.id) جای خالی NULL را نمی‌شمارد و 2، 0، 0 می‌دهد. COUNT(*) سطر نگه‌داشته‌شده را می‌شمارد و برای کتاب بی‌امانت یک می‌دهد. عبارت شمارش را آگاهانه انتخاب کنید.','Python دوه پورونه لري او نور یې نه لري. COUNT(l.id) د NULL ځای نه شمېري او 2، 0، 0 ورکوي. COUNT(*) ساتل شوی کتار شمېري او بې پوره کتاب ته یو ورکوي. د شمېرلو عبارت په پوهه وټاکئ.'),t('Return only books with no loans using the left-join result.','از نتیجهٔ وصل چپ فقط کتاب‌های بدون امانت را برگردانید.','له کیڼ نښلونې یوازې بې پوره کتابونه ورکړئ.')),
sqlmod(t('NULL and missing information','NULL و معلومات ناموجود','NULL او ورک معلومات'),t('NULL represents missing or unknown information; it is not zero or an empty string. Use IS NULL rather than = NULL. Comparisons with unknown values do not behave like ordinary true/false arithmetic. COALESCE can provide a display fallback, but it should not silently replace unknown business facts.', 'NULL معلومات ناموجود یا نامعلوم است، نه صفر یا متن خالی. IS NULL بنویسید، نه = NULL. مقایسه با نامعلوم مثل مقایسهٔ عادی نیست. COALESCE مقدار نمایشی جایگزین می‌دهد، اما نباید واقعیت کاری نامعلوم را پنهانی عوض کند.', 'NULL ورک یا نامعلوم معلومات دي، صفر یا تش متن نه دی. IS NULL وکاروئ، نه = NULL. له نامعلوم سره پرتله د عادي پرتله په شان نه ده. COALESCE د ښودلو بدیل ورکوي، خو نامعلوم کاري حقیقت باید پټ بدل نه کړي.'),'ALTER TABLE books ADD COLUMN note TEXT;\nSELECT title,COALESCE(note,\'No note\') AS note FROM books WHERE note IS NULL ORDER BY id;',t('The added column has no supplied values, so all notes are NULL. IS NULL keeps all three rows and COALESCE displays No note. The underlying notes remain NULL. A later empty string would not match IS NULL, demonstrating why empty and unknown need separate rules.','ستون تازه مقدار ندارد و همهٔ یادداشت‌ها NULL اند. IS NULL هر سه سطر را می‌گیرد و COALESCE متن No note نشان می‌دهد. ذخیره هنوز NULL است. متن خالی بعدی با IS NULL مطابق نمی‌شود؛ خالی و نامعلوم قواعد جدا می‌خواهند.','نوې ستنه ارزښت نه لري او ټول یادښتونه NULL دي. IS NULL درې واړه اخلي او COALESCE د No note متن ښيي. ساتل شوی ارزښت لا NULL دی. وروسته تش متن له IS NULL سره نه برابرېږي؛ تش او نامعلوم جلا قواعد غواړي.'),t('Compare a NULL note and an empty note without treating them as equal.','یادداشت NULL و خالی را بدون برابر دانستن مقایسه کنید.','NULL او تش یادښت بې برابر ګڼلو پرتله کړئ.')),
sqlmod(t('Safe changes and parameters','تغییر امن و پارامتر','خوندي بدلون او پارامتر'),t('UPDATE changes existing rows and DELETE removes them. A missing WHERE can affect the whole table. Preview the intended rows first and use a transaction for related changes. In application code bind user values as parameters instead of assembling them into SQL command text.', 'UPDATE سطر موجود را تغییر و DELETE حذف می‌کند. نبود WHERE می‌تواند همهٔ جدول را تغییر بدهد. نخست سطرهای هدف را ببینید و تغییر مرتبط را در معامله بگذارید. در کود برنامه مقدار کاربر را با پارامتر بدهید، نه با چسپاندن در متن SQL.', 'UPDATE موجود کتار بدلوي او DELETE یې ړنګوي. بې WHERE ټول جدول اغېزمنېدای شي. لومړی هدف کتارونه وګورئ او تړلي بدلونونه معامله کړئ. په اپ کې د کارن ارزښت د پارامتر له لارې ورکړئ، د SQL متن ته یې مه نښلوئ.'),'BEGIN;\nUPDATE books SET price=120 WHERE id=1;\nCOMMIT;\nSELECT id,price FROM books ORDER BY id;',t('Only id 1 becomes 120; ids 2 and 3 remain 150 and 100. The literal is fixed lesson data. For a real user value use a driver placeholder such as ? with a separate bound value; placeholders are supplied by the calling API, not quoted inside the command.','فقط id برابر 1 به 120 می‌رسد؛ 2 و 3 همان 150 و 100 می‌مانند. مقدار نمونه ثابت است. برای ورودی واقعی علامت پارامتر مانند ? و مقدار جدا به API بدهید؛ پارامتر را در نقل قول داخل دستور نگذارید.','یوازې id=1 د 120 ارزښت اخلي؛ 2 او 3 په 150 او 100 پاتې دي. د درس مقدار ثابت دی. واقعي داخلې ته د ? په شان پارامتر او جلا ارزښت API ته ورکړئ؛ پارامتر په قومانده کې نقل قول ته مه اچوئ.'),t('Preview book 3, change its price in a transaction, and verify other rows.','کتاب 3 را ببینید، قیمتش را در معامله تغییر و سطرهای دیگر را بررسی کنید.','کتاب 3 وګورئ، بیه یې په معامله کې بدله او نور کتارونه وګورئ.'))
], [
project(t('Library query workbook','دفتر پرس‌وجوی کتابخانه','د کتابتون د پوښتنو کتابچه'),t('Produce useful reports from fictional books and loans.','از کتاب و امانت فرضی گزارش مفید بسازید.','له فرضي کتابونو او پورونو ګټور راپورونه جوړ کړئ.'),[t('Write ordered title and price filters.','فلتر مرتب عنوان و قیمت بنویسید.','مرتب نوم او بیه چاڼونه ولیکئ.'),t('Include books with zero loans in a loan-count report.','کتاب بی‌امانت را در گزارش تعداد امانت شامل کنید.','بې پوره کتاب د پور شمېر راپور کې شامل کړئ.'),t('Explain every join and test duplicate matching rows.','هر وصل را توضیح و چند مطابق را آزمایش کنید.','هره نښلونه تشریح او څو برابر کتارونه وازمویئ.')]),
project(t('AFN expense reports','گزارش مصرف افغانی','د افغانیو لګښت راپورونه'),t('Report fictional household spending by category and date.','مصرف فرضی خانواده را به کتگوری و تاریخ گزارش کنید.','د فرضي کورنۍ لګښت د کتګورۍ او نېټې له مخې راپور کړئ.'),[t('Store amounts as integer AFN and reject negative expenses.','مبلغ صحیح افغانی ذخیره و مصرف منفی را رد کنید.','مبلغ په صحیح افغانیو وساتئ او منفي مصرف رد کړئ.'),t('Test empty periods and inclusive date boundaries.','دورهٔ خالی و مرز شامل تاریخ را آزمایش کنید.','تشه موده او شاملې نېټې پولې وازمویئ.'),t('Reconcile grouped totals with the overall total.','مجموع گروه‌ها را با مجموع عمومی برابر بررسی کنید.','د ډلو مجموعې له عمومي مجموعې سره برابرې وګورئ.')]),
project(t('Enrollment reporting desk','گزارش ثبت‌نام','د نوم‌لیکنې راپور'),t('Answer course enrollment questions without losing courses that have no students.','پرسش ثبت‌نام را بدون حذف کورس بی‌شاگرد جواب بدهید.','د نوم‌لیکنې پوښتنې بې زده کوونکي کورس له ورکېدو پرته ځواب کړئ.'),[t('Use a left join to retain empty courses.','با وصل چپ کورس خالی را نگه دارید.','په کیڼ نښلونه تش کورس وساتئ.'),t('Count enrollments without counting NULL placeholders.','ثبت‌نام را بدون شمردن جای NULL بشمارید.','نوم‌لیکنې د NULL ځای له شمېرلو پرته وشمېرئ.'),t('Document query inputs, expected rows, and ordering.','ورودی، سطر مورد انتظار و ترتیب را ثبت کنید.','داخله، تمه شوي کتارونه او ترتیب ثبت کړئ.')])])

c('sqlite',t('SQLite for Offline Apps','SQLite برای برنامهٔ آفلاین','SQLite د آفلاین اپونو لپاره'),'sql',LOCAL,[
sqlmod(t('Embedded storage and connections','ذخیرهٔ داخلی و اتصال','دنننۍ ساتنه او اتصال'),t('SQLite runs inside a program rather than requiring a separate database server. A file database can survive restart; an in-memory database disappears when its connection closes. Choose deliberately. Lessons use fresh temporary data so an experiment cannot alter the learner progress database.', 'SQLite داخل پروگرام کار می‌کند و سرور جدا نمی‌خواهد. دیتابیس فایل پس از بازشدن دوباره باقی می‌ماند؛ دیتابیس حافظه با بستن اتصال از بین می‌رود. آگاهانه انتخاب کنید. درس معلومات تازهٔ موقت دارد تا پیشرفت شاگرد تغییر نکند.', 'SQLite د پروګرام دننه چلېږي او جلا سرور نه غواړي. فایلي ډیټابېس له بیا پرانیستلو وروسته پاتې وي؛ حافظوي د اتصال په تړلو ورکېږي. په پوهه یې وټاکئ. درس تازه موقتي معلومات لري څو د زده کوونکي پرمختګ بدل نه شي.'),'SELECT COUNT(*) AS book_count FROM books;',t('The fresh fixture contains three books, so the count is 3. Reopening a memory connection would start empty, while reopening a saved file should retain committed rows. Test those lifetimes separately; seeing data in one open connection is not evidence of restart persistence.','نمونهٔ تازه سه کتاب دارد و تعداد 3 است. اتصال حافظهٔ تازه خالی است، اما فایل ذخیره‌شده باید ثبت تأییدشده را نگه دارد. عمرها را جدا آزمایش کنید؛ دیدن معلومات در یک اتصال ثابت نمی‌کند پس از بازشدن می‌ماند.','تازه نمونه درې کتابونه لري او شمېر 3 دی. نوی حافظوي اتصال تش وي، خو ساتل شوی فایل باید منل شوي ثبتونه وساتي. عمرونه جلا وازمویئ؛ په یوه اتصال کې معلومات لیدل د بیا پرانیستلو ساتنه نه ثابتوي.'),t('Compare a temporary database and a file database after closing their connections.','دیتابیس موقت و فایل را پس از بستن اتصال مقایسه کنید.','موقتي او فایلي ډیټابېس د اتصال له تړلو وروسته پرتله کړئ.')),
sqlmod(t('Types and application constraints','نوع و محدودیت برنامه','ډولونه او د اپ محدودیتونه'),t('SQLite type affinity is flexible; a declared column type is not a complete validation policy. Combine suitable types, NOT NULL, CHECK, and application validation. For integer AFN, reject fractional and negative inputs before storage. A database schema should express the data contract that the app actually needs.', 'نوع در SQLite انعطاف دارد؛ نوع اعلام‌شده سیاست کامل بررسی نیست. نوع مناسب، NOT NULL، CHECK و بررسی برنامه را ترکیب کنید. برای افغانی صحیح، مقدار کسری و منفی را پیش از ذخیره رد کنید. ساختار باید قرارداد واقعی برنامه را بیان کند.', 'په SQLite کې ډول نرم دی؛ اعلان شوی ډول بشپړه کتنه نه ده. مناسب ډول، NOT NULL، CHECK او د اپ کتنه یوځای کړئ. د صحیح افغانیو لپاره کسري او منفي داخله له ساتلو مخکې رد کړئ. جوړښت باید د اپ واقعي تړون بیان کړي.'),'SELECT title,typeof(price) AS stored_type FROM books ORDER BY id;',t('The inserted prices have integer storage type. That observation covers these rows only. To require integer storage, add a CHECK using typeof where appropriate or a suitable strict schema, and test hostile inputs. Do not conclude that a text declaration alone validates every future value.','قیمت‌های واردشده نوع ذخیرهٔ integer دارند. این مشاهده فقط همین سطرها را پوشش می‌دهد. برای الزام صحیح بودن، CHECK مناسب typeof یا ساختار سخت‌گیر اضافه و ورودی خراب آزمایش کنید. اعلان نوع به‌تنهایی همهٔ مقدارهای آینده را تضمین نمی‌کند.','داخلې شوې بیې integer ډول لري. دا یوازې همدا کتارونه پوښي. د صحیح ساتنې د الزام لپاره مناسب typeof CHECK یا سخت جوړښت ورزیات او خرابې داخلې وازمویئ. یوازې ډول اعلانول ټول راتلونکي مقدارونه نه تضمینوي.'),t('Require integer nonnegative prices and test text and fractional values.','قیمت صحیح غیرمنفی را لازم و متن و کسر را آزمایش کنید.','صحیح غیرمنفي بیه لازمه او متن او کسري ارزښتونه وازمویئ.')),
sqlmod(t('Transactions and competing writers','معامله و نویسنده‌های هم‌زمان','معامله او هممهاله لیکونکي'),t('SQLite allows only one writer at a time. Keep transactions short and avoid waiting for user input while holding a write transaction. A conditional update can enforce available stock at the point of change. Check affected rows; a completed command that changed zero rows is not a successful sale.', 'SQLite در یک وقت یک نویسنده اجازه می‌دهد. معامله را کوتاه نگه دارید و هنگام نوشتن منتظر کاربر نمانید. تغییر شرطی موجودی را در لحظهٔ تغییر بررسی می‌کند. تعداد سطر تغییرکرده را ببینید؛ صفر سطر به معنی فروش موفق نیست.', 'SQLite په یوه وخت یو لیکونکی مني. معاملې لنډې وساتئ او د لیکلو معامله کې کارن ته انتظار مه کوئ. شرطي بدلون موجودي د بدلون په شېبه ګوري. اغېزمن کتارونه وګورئ؛ صفر بدل شوي کتارونه بریالی پلور نه دی.'),'BEGIN IMMEDIATE;\nUPDATE books SET price=price-10 WHERE id=1 AND price>=10;\nCOMMIT;\nSELECT price FROM books WHERE id=1;',t('The immediate transaction requests the write lock before changing data. Book 1 becomes 90 because it meets the condition. A competing writer must wait or receive a busy error according to connection policy. Test a retry without duplicating the business operation.','معاملهٔ فوری پیش از تغییر قفل نوشتن می‌خواهد. کتاب 1 چون شرط دارد به 90 می‌رسد. نویسندهٔ دیگر بر اساس سیاست اتصال منتظر می‌ماند یا خطای مشغول می‌گیرد. تلاش دوباره را بدون تکرار عملیات کاری آزمایش کنید.','فوري معامله له بدلون مخکې د لیکلو قلف غواړي. کتاب 1 شرط پوره کوي او 90 کېږي. بل لیکونکی د اتصال تګلارې له مخې انتظار یا busy خطا اخلي. بیا هڅه د کاري عملیاتو له تکرار پرته وازمویئ.'),t('Test an update whose condition matches no rows and report that outcome accurately.','تغییر با صفر سطر مطابق را آزمایش و نتیجه را درست گزارش کنید.','بې برابر کتاره بدلون وازمویئ او پایله سمه ووایئ.')),
sqlmod(t('Indexes and query plans','اندکس و طرح پرس‌وجو','اندکس او د پوښتنې پلان'),t('An index keeps an additional searchable structure. It can speed some reads but costs space and write work. Start from a real query and inspect its plan. A tiny table may be faster to scan; do not force an index merely because indexes sound advanced.', 'اندکس ساختار جستجوی اضافی نگه می‌دارد. بعضی خواندن‌ها را تیز می‌کند، اما فضا و کار نوشتن می‌خواهد. از پرس‌وجوی واقعی آغاز و طرح آن را ببینید. جدول کوچک ممکن است با مرور کامل تیزتر باشد؛ اندکس را فقط برای پیشرفته بودن تحمیل نکنید.', 'اندکس اضافي لټون جوړښت ساتي. ځینې لوستل تېزوي، خو ځای او لیکلو کار غواړي. له واقعي پوښتنې پیل او پلان یې وګورئ. کوچنی جدول په بشپړ لوستلو تېز کېدای شي؛ یوازې د پرمختللي نوم لپاره اندکس مه تحمیلوئ.'),'CREATE INDEX books_price ON books(price);\nEXPLAIN QUERY PLAN SELECT title FROM books WHERE price=100;',t('The plan describes how SQLite intends to find matching prices; it is not the list of books. Exact wording can vary by SQLite version and statistics. Compare with the plan before the index and measure a realistic fixture. The result rows should remain the same with or without the index.','طرح روش یافتن قیمت را توضیح می‌دهد، نه فهرست کتاب را. متن دقیق به نسخه و آمار وابسته است. با طرح پیش از اندکس مقایسه و نمونهٔ واقعی را اندازه بگیرید. نتیجهٔ سطرها باید با اندکس و بدون آن یکسان بماند.','پلان د بیو موندلو لاره ښيي، د کتابونو لېست نه دی. دقیق متن له نسخې او احصایې سره بدلېږي. له اندکس مخکې پلان سره یې پرتله او واقعي نمونه اندازه کړئ. پایله کتارونه باید له اندکس سره او بې هغه یو شان وي.'),t('Compare query plans before and after a price index without changing query results.','طرح پیش و پس اندکس قیمت را بدون تغییر نتیجه مقایسه کنید.','د بیې اندکس مخکې او وروسته پلان بې پایلې بدلولو پرتله کړئ.')),
sqlmod(t('Schema migrations','تغییر نسخهٔ ساختار','د جوړښت نسخه بدلول'),t('A new app release may need another column while retaining old records. A migration is an ordered transformation of an older schema. Version it and test it on real old fixtures, not only a fresh empty database. Never erase a user database as a shortcut for a failed migration.', 'نسخهٔ تازه ممکن است ستون دیگر با حفظ ثبت قبلی بخواهد. مهاجرت ساختار تبدیل مرتب نسخهٔ قدیمی است. نسخه بدهید و روی نمونهٔ قدیمی آزمایش کنید، نه فقط دیتابیس تازهٔ خالی. پاک کردن دیتابیس راه‌حل کوتاه ناکامی مهاجرت نیست.', 'نوې نسخه له پخوانیو ثبتونو ساتلو سره نوې ستنه غوښتلای شي. مهاجرت د زاړه جوړښت مرتب بدلون دی. نسخه ورکړئ او په زاړه نمونه یې وازمویئ، نه یوازې نوي تش ډیټابېس. د کارن ډیټابېس ړنګول د ناکام مهاجرت لنډه لار نه ده.'),'BEGIN;\nALTER TABLE books ADD COLUMN active INTEGER NOT NULL DEFAULT 1;\nCOMMIT;\nSELECT id,active FROM books ORDER BY id;',t('The new active column gives each of the three old rows the default 1. Existing titles and prices remain. Running the same ALTER blindly a second time fails because the column exists. Track schema version and only apply the relevant step, then test reopening the migrated file.','ستون active تازه به هر سه سطر قدیمی مقدار 1 می‌دهد و عنوان و قیمت می‌مانند. اجرای دوبارهٔ بی‌بررسی ALTER خطا می‌دهد چون ستون موجود است. نسخهٔ ساختار را ثبت و فقط مرحلهٔ لازم را اجرا کنید، سپس فایل تازه‌شده را باز کنید.','نوې active ستنه درې واړو زړو کتارونو ته 1 ورکوي او نوم او بیه پاتې دي. د ALTER ړوند تکرار خطا ورکوي ځکه ستنه شته. د جوړښت نسخه وساتئ او یوازې اړین ګام وچلوئ، بیا بدل شوی فایل پرانیزئ.'),t('Migrate an old fixture and verify all titles, prices, and defaults after reopening.','نمونهٔ قدیمی را تبدیل و پس از بازشدن عنوان، قیمت و پیش‌فرض را بررسی کنید.','زړه نمونه بدله او له بیا پرانیستلو وروسته نومونه، بیې او ډیفالټ وګورئ.')),
sqlmod(t('Backup verification and recovery','بررسی پشتیبان و بازیابی','د بیک اپ کتنه او راګرځول'),t('A backup is useful only if it restores correctly. Use a supported backup mechanism or export from a consistent snapshot. Copying one live database file while a journal or WAL is active may miss data. Validate restored structure and business totals in a separate training copy before replacing anything.', 'پشتیبان وقتی مفید است که درست برگردد. از روش پشتیبان معتبر یا عکس سازگار استفاده کنید. کاپی یک فایل زنده هنگام فعال بودن journal یا WAL ممکن است معلومات کم داشته باشد. ساختار و مجموع کاری را در کاپی جدا بررسی کنید.', 'بیک اپ هغه وخت ګټور دی چې سم راګرځي. ملاتړ شوې لاره یا برابر snapshot وکاروئ. د فعال journal یا WAL پر مهال د یوه ژوندي فایل کاپي معلومات کمولای شي. جوړښت او کاري مجموعې په جلا کاپي کې وګورئ.'),'PRAGMA integrity_check;\nSELECT COUNT(*) AS rows,SUM(price) AS total FROM books;',t('integrity_check should report ok for this fixture; the business check reports 3 rows and total 350. Structural integrity alone does not prove that the right records were backed up. Record both counts and domain totals and compare them after restoring a separate copy.','integrity_check برای نمونه ok می‌دهد و بررسی کاری 3 سطر و مجموع 350 است. درستی ساختار ثابت نمی‌کند ثبت درست پشتیبان شده است. تعداد و مجموع کاری را ثبت و پس از بازگردانی کاپی جدا مقایسه کنید.','integrity_check د نمونې لپاره ok او کاري کتنه 3 کتارونه او 350 مجموعه ورکوي. د جوړښت سموالی د سمو ثبتونو بیک اپ نه ثابتوي. شمېر او کاري مجموعې ثبت او له جلا راګرځولو وروسته یې پرتله کړئ.'),t('Restore a training backup and compare its row count and total with the source.','پشتیبان تمرینی را برگردانید و تعداد و مجموع را با اصل مقایسه کنید.','تمریني بیک اپ را وګرځوئ او شمېر او مجموعه له اصل سره پرتله کړئ.'))
], [
project(t('Offline notes database','دیتابیس یادداشت آفلاین','د آفلاین یادښت ډیټابېس'),t('Persist fictional notes and restore them after restarting a local app.','یادداشت فرضی را ذخیره و پس از بازشدن برنامه بخوانید.','فرضي یادښتونه وساتئ او له بیا پرانیستلو وروسته یې ولولئ.'),[t('Validate titles and use parameterized writes.','عنوان را بررسی و نوشتن پارامتری استفاده کنید.','نوم وګورئ او پارامتري لیکنه وکاروئ.'),t('Test save failure without losing the previous note.','ناکامی ذخیره را بدون گم‌شدن یادداشت قبلی آزمایش کنید.','ناکامه ساتنه د زاړه یادښت له ورکېدو پرته وازمویئ.'),t('Migrate a populated older schema.','ساختار قدیمی دارای معلومات را تبدیل کنید.','له معلوماتو ډک زوړ جوړښت بدل کړئ.')]),
project(t('Transactional stock ledger','دفتر موجودی معاملاتی','معاملاتي موجودي دفتر'),t('Record a sale and stock reduction as one local operation.','فروش و کاهش موجودی را یک عملیات محلی ثبت کنید.','پلور او موجودي کمول د یوه محلي عمل په توګه ثبت کړئ.'),[t('Prevent overselling with a conditional update.','با تغییر شرطی فروش بیش از موجودی را منع کنید.','په شرطي بدلون له موجودۍ ډېر پلور منع کړئ.'),t('Roll back the stock change if sale insertion fails.','اگر ثبت فروش ناکام شد تغییر موجودی را لغو کنید.','که پلور ثبت ناکام شي، موجودي بدلون لغوه کړئ.'),t('Test two competing connections and a repeated request.','دو اتصال رقابتی و درخواست تکراری را آزمایش کنید.','دوه سیال اتصالونه او تکراري غوښتنه وازمویئ.')]),
project(t('Migration and restore kit','بستهٔ تغییر ساختار و بازیابی','د جوړښت بدلون او راګرځولو بسته'),t('Deliver fixtures and a repeatable upgrade-and-restore procedure.','نمونه و روش تکرارپذیر ارتقا و بازیابی تحویل بدهید.','نمونې او تکرارېدونکې لوړولو او راګرځولو لاره وسپارئ.'),[t('Keep versioned fixtures for each supported schema.','برای هر ساختار پشتیبانی‌شده نمونهٔ نسخه‌دار نگه دارید.','د هر ملاتړ شوي جوړښت نسخه لرونکې نمونه وساتئ.'),t('Compare row counts and totals after restore.','پس از بازیابی تعداد و مجموع را مقایسه کنید.','له راګرځولو وروسته شمېر او مجموعه پرتله کړئ.'),t('Document a failed migration without erasing the original.','مهاجرت ناکام را بدون پاک کردن اصل ثبت کنید.','ناکام مهاجرت د اصل له پاکولو پرته ثبت کړئ.')])])

# Server-specific courses are deliberately distinguished from in-app SQLite.
c('postgresql',t('PostgreSQL Development','توسعه با PostgreSQL','په PostgreSQL پراختیا'),'sql',PG,[
module(t('Server, database, and schema','سرور، دیتابیس و ساختار','سرور، ډیټابېس او سکیما'),t('PostgreSQL is a database server. A client such as psql connects to a particular database as a role. Schemas organize objects inside that database. A local server can work without internet, but it must already be installed and running. A connection failure is not corrected by rewriting a valid SELECT.', 'PostgreSQL سرور دیتابیس است. مشتری مانند psql با نقش مشخص به دیتابیس وصل می‌شود. schema اشیا را داخل آن منظم می‌کند. سرور محلی بی‌انترنت کار می‌کند، اما باید نصب و فعال باشد. خطای اتصال با بازنویسی SELECT درست اصلاح نمی‌شود.', 'PostgreSQL د ډیټابېس سرور دی. psql مشتری د یوه رول په توګه ټاکلي ډیټابېس ته نښلي. schema دننه شیان منظموي. محلي سرور بې انټرنېټه کار کوي، خو باید نصب او روان وي. د اتصال خطا د سم SELECT په بیا لیکلو نه سمېږي.'),'SELECT current_database(),current_user;\nCREATE TEMP TABLE books(id integer PRIMARY KEY,title text NOT NULL);\nINSERT INTO books VALUES(1,\'Python\');\nSELECT title FROM books;',t('The first query identifies the actual connection, so its values depend on your setup. The temporary table belongs to this session. Inserting one book and selecting its title returns Python. Ending the session removes the temporary table; use a deliberate persistent schema for a real application.','پرس‌وجوی اول اتصال واقعی را نشان می‌دهد؛ مقدار به محیط شما وابسته است. جدول موقت مربوط به همین جلسه است. یک کتاب وارد و Python خوانده می‌شود. پایان جلسه جدول را حذف می‌کند؛ برای برنامهٔ واقعی ساختار دایمی طراحی کنید.','لومړۍ پوښتنه واقعي اتصال ښيي؛ ارزښتونه په چاپېریال پورې اړه لري. موقتي جدول د همدې ناستې دی. یو کتاب داخل او Python لوستل کېږي. د ناستې پای جدول لرې کوي؛ واقعي اپ ته دایمي جوړښت طرحه کړئ.'),t('Identify the connected database and create a disposable one-row table.','دیتابیس وصل‌شده را بشناسید و جدول موقت یک‌سطری بسازید.','نښتی ډیټابېس وپېژنئ او موقتي یو کتاره جدول جوړ کړئ.')),
module(t('Typed schemas and constraints','ساختار نوع‌دار و محدودیت','ډول لرونکی جوړښت او محدودیت'),t('Choose column types for meaning, not appearance. Integer quantities and numeric monetary values have different contracts. A generated identity creates identifiers; it does not validate other fields. Put required and nonnegative rules into constraints and handle their failures in the client without losing the draft.', 'نوع ستون را برای معنی انتخاب کنید، نه ظاهر. تعداد صحیح و مبلغ عددی قرارداد متفاوت دارند. شناسهٔ تولیدشده هویت می‌سازد، نه بررسی همهٔ فیلدها. الزام و غیرمنفی بودن را محدودیت کنید و خطا را بدون گم‌شدن پیش‌نویس مدیریت کنید.', 'د ستنې ډول د مانا لپاره وټاکئ، نه بڼې. صحیح شمېر او مالي عدد بېل تړونونه لري. تولید شوی پېژند هویت جوړوي، نورې خانې نه ګوري. اړین او غیرمنفي قواعد محدودیت کړئ او خطا بې مسودې ورکېدو اداره کړئ.'),'CREATE TEMP TABLE expenses(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,amount numeric(12,2) NOT NULL CHECK(amount>=0));\nINSERT INTO expenses(amount) VALUES(20.50) RETURNING id,amount;',t('The server supplies the identity and returns the inserted row. In this fresh table the first id is 1 and amount is 20.50. Numeric scale preserves the specified decimal precision; a UI string still needs validation. Try a negative amount and expect a constraint error.','سرور شناسه می‌دهد و سطر واردشده را برمی‌گرداند. در جدول تازه شناسهٔ اول 1 و مبلغ 20.50 است. مقیاس عددی دقت اعشار مشخص را نگه می‌دارد؛ متن ورودی هنوز بررسی می‌خواهد. مبلغ منفی باید خطای محدودیت بدهد.','سرور پېژند ورکوي او داخل شوی کتار بېرته ورکوي. په تازه جدول کې لومړی پېژند 1 او مبلغ 20.50 دی. عددي مقیاس ټاکلې اعشاري دقت ساتي؛ متني داخله لا کتنه غواړي. منفي مبلغ باید د محدودیت خطا ورکړي.'),t('Insert a valid expense and demonstrate rejection of a negative one.','مصرف معتبر وارد و رد مصرف منفی را نشان بدهید.','معتبر لګښت داخل او د منفي رد وښيئ.')),
module(t('Joins and window calculations','وصل و محاسبهٔ پنجره‌ای','نښلونې او کړکۍ حساب'),t('An aggregate can collapse rows into groups. A window calculation instead attaches a result while retaining individual rows. For a running total, specify ordering and the frame so the business meaning is clear. Unique ordering avoids ambiguity when several records share a date.', 'جمع گروهی سطرها را در گروه خلاصه می‌کند. محاسبهٔ پنجره‌ای نتیجه را با حفظ هر سطر اضافه می‌کند. برای مجموع جاری ترتیب و محدوده را صریح بدهید. ترتیب یکتا ابهام ثبت‌های هم‌تاریخ را رفع می‌کند.', 'ګروپي جمع کتارونه په ډلو لنډوي. کړکۍ حساب د هر کتار په ساتلو پایله ورزیاتوي. روانې مجموعې ته ترتیب او چوکاټ څرګند کړئ. یکتا ترتیب د یوې نېټې ثبتونو ابهام لرې کوي.'),'SELECT id,amount,SUM(amount) OVER(ORDER BY id ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running_total FROM (VALUES(1,10),(2,20),(3,5)) AS e(id,amount) ORDER BY id;',t('Three rows remain visible. The running totals are 10, 30, and 35 because each frame begins at the first row and ends at the current row. A plain SUM without a window would give a single total. The explicit id order makes this example deterministic.','هر سه سطر باقی می‌مانند. مجموع جاری 10، 30 و 35 است چون محدوده از اول تا سطر فعلی است. SUM ساده بدون پنجره یک مجموع می‌دهد. ترتیب صریح id نمونه را ثابت می‌سازد.','درې واړه کتارونه پاتې دي. روانې مجموعې 10، 30 او 35 دي ځکه چوکاټ له لومړي تر اوسني کتاره دی. بې کړکۍ ساده SUM یوه مجموعه ورکوي. څرګند id ترتیب نمونه ثابتوي.'),t('Add a fourth amount and predict its running total before execution.','مبلغ چهارم اضافه و مجموع جاری را پیش از اجرا پیش‌بینی کنید.','څلورم مبلغ زیات او روانه مجموعه له اجرا مخکې اټکل کړئ.')),
module(t('Transactions and row locks','معامله و قفل سطر','معامله او د کتار قلف'),t('Concurrent clients can read the same old quantity. A row lock can protect a read-then-write operation while its transaction is active. Locks must be released by commit or rollback. Keep the transaction short and plan how to report a conflict or retry; waiting indefinitely is not a usable interface.', 'مشتری هم‌زمان می‌تواند همان تعداد قدیمی را بخواند. قفل سطر خواندن و بعد نوشتن را در معامله محافظت می‌کند. با تأیید یا لغو قفل آزاد می‌شود. معامله کوتاه و راه گزارش تعارض یا تلاش دوباره لازم است؛ انتظار بی‌پایان رابط مفید نیست.', 'هممهاله مشتریان یو زوړ شمېر لوستلای شي. د کتار قلف په معامله کې لوستل او بیا لیکل ساتي. په تایید یا لغوه کولو قلف خوشې کېږي. معامله لنډه او د ټکر یا بیا هڅې لاره ولرئ؛ بې پایه انتظار ګټور مخ نه دی.'),'CREATE TEMP TABLE stock(id integer PRIMARY KEY,quantity integer CHECK(quantity>=0));\nINSERT INTO stock VALUES(1,5);\nBEGIN;\nSELECT quantity FROM stock WHERE id=1 FOR UPDATE;\nUPDATE stock SET quantity=quantity-2 WHERE id=1;\nCOMMIT;\nSELECT quantity FROM stock;',t('The transaction locks the selected row, reads 5, reduces it to 3, and commits. This one-session example illustrates the sequence; it does not prove concurrent behavior. Use a shared disposable table and two sessions for a real lock test, since temporary tables are session-local.','معامله سطر را قفل، 5 را می‌خواند، به 3 کم و تأیید می‌کند. نمونهٔ یک‌جلسه‌ای ترتیب را نشان می‌دهد، نه هم‌زمانی را. برای آزمون واقعی دو جلسه و جدول تمرینی مشترک لازم است؛ جدول موقت مخصوص جلسه است.','معامله کتار قلف کوي، 5 لولي، 3 ته یې کموي او تاییدوي. یوه ناسته یوازې ترتیب ښيي، هممهالي نه ثابتوي. واقعي ازموینې ته دوه ناستې او ګډ تمریني جدول پکار دی؛ موقتي جدول د خپلې ناستې دی.'),t('Demonstrate lock waiting with two sessions on a disposable shared table.','انتظار قفل را با دو جلسه روی جدول تمرینی مشترک نشان بدهید.','په ګډ تمریني جدول د دوو ناستو د قلف انتظار وښيئ.')),
module(t('Indexes and EXPLAIN','اندکس و EXPLAIN','اندکس او EXPLAIN'),t('EXPLAIN describes a planned execution strategy. EXPLAIN ANALYZE actually runs the statement and measures it, so it is not a harmless description for a modifying query. Begin with read-only queries and realistic fixtures. More indexes can slow inserts and updates, so compare both read and write costs.', 'EXPLAIN طرح اجرا را توضیح می‌دهد. EXPLAIN ANALYZE واقعاً اجرا و اندازه می‌گیرد؛ برای تغییر معلومات فقط توضیح بی‌اثر نیست. از پرس‌وجوی خواندنی و نمونهٔ واقعی شروع کنید. اندکس بیشتر نوشتن را کند می‌کند؛ هزینهٔ خواندن و نوشتن را مقایسه کنید.', 'EXPLAIN د اجرا پلان ښيي. EXPLAIN ANALYZE په رښتیا اجرا او اندازه کوي؛ بدلوونکې پوښتنې ته بې اغېزې تشریح نه ده. له لوستونکو پوښتنو او واقعي نمونو پیل کړئ. ډېر اندکسونه لیکل ورو کوي؛ د لوستلو او لیکلو لګښت پرتله کړئ.'),'CREATE TEMP TABLE products(id integer PRIMARY KEY,price integer);\nINSERT INTO products SELECT n,n%100 FROM generate_series(1,1000) AS n;\nCREATE INDEX ON products(price);\nANALYZE products;\nEXPLAIN SELECT id FROM products WHERE price=42;',t('The fixture has 1000 rows and an index on price. ANALYZE collects statistics; EXPLAIN then reports the chosen plan. The exact plan depends on the server and statistics, so do not grade by a copied plan string. Verify the returned records separately from performance.','نمونه 1000 سطر و اندکس قیمت دارد. ANALYZE آمار جمع و EXPLAIN طرح انتخابی می‌دهد. طرح دقیق به سرور و آمار وابسته است؛ با متن کاپی‌شده نمره ندهید. درستی ثبت نتیجه را از سرعت جدا بررسی کنید.','نمونه 1000 کتارونه او د بیې اندکس لري. ANALYZE احصایه ټولوي او EXPLAIN ټاکلی پلان ښيي. دقیق پلان له سرور او احصایې سره تړلی دی؛ په کاپي پلان نمره مه ورکوئ. د پایلې ثبتونه له سرعت جلا وګورئ.'),t('Compare a selective query with and without an index on a training fixture.','پرس‌وجوی انتخابی را با اندکس و بدون آن در نمونهٔ تمرینی مقایسه کنید.','ټاکونکې پوښتنه په تمریني نمونه کې له اندکس سره او بې هغه پرتله کړئ.')),
module(t('Roles, backup, and restore','نقش، پشتیبان و بازیابی','رول، بیک اپ او راګرځول'),t('A role controls permissions; an application should not connect with unrestricted administrative power. Backups need a tested restore procedure and protected local storage. Logical export and restore are separate tools, not SQL SELECT statements. Use fictional data and restore into a different training database before trusting the process.', 'نقش صلاحیت را کنترول می‌کند؛ برنامه نباید با قدرت نامحدود مدیر وصل شود. پشتیبان روش بازیابی آزمایش‌شده و ذخیرهٔ محلی محافظت‌شده می‌خواهد. صدور و بازیابی ابزار جدا اند، نه SELECT. معلومات فرضی را در دیتابیس تمرینی دیگر برگردانید.', 'رول صلاحیت کنټرولوي؛ اپ باید په نامحدود اداري ځواک ونه نښلي. بیک اپ ازمویل شوې راګرځونه او خوندي محلي ساتنه غواړي. صادرول او راګرځول جلا وسایل دي، SELECT نه دي. فرضي معلومات بل تمریني ډیټابېس ته را وګرځوئ.'),'-- Shell commands, not SQL. Replace names with disposable training databases.\npg_dump -Fc training_source -f training.dump\npg_restore --no-owner --dbname=training_restore training.dump',t('pg_dump writes a custom-format archive. pg_restore reads it into a separately prepared target. These commands require permissions and connection settings and do not create a complete access policy. Compare restored row counts, constraints, and representative reports; archive creation alone is not a successful recovery test.','pg_dump آرشیف می‌نویسد و pg_restore در مقصد جدا و آماده می‌خواند. دستورها صلاحیت و تنظیم اتصال می‌خواهند و سیاست کامل دسترسی نمی‌سازند. تعداد سطر، محدودیت و گزارش نمونه را مقایسه کنید؛ ساخت آرشیف به‌تنهایی بازیابی موفق نیست.','pg_dump ارشیف لیکي او pg_restore یې جلا چمتو هدف ته لولي. قوماندې صلاحیت او اتصال تنظیم غواړي او بشپړه لاسرسي تګلاره نه جوړوي. شمېر، محدودیتونه او نمونه راپورونه پرتله کړئ؛ یوازې ارشیف جوړول بریالۍ راګرځونه نه ده.'),t('Restore a fictional database to a separate target and test a restricted reader role.','دیتابیس فرضی را در مقصد جدا برگردانید و نقش خوانندهٔ محدود را آزمایش کنید.','فرضي ډیټابېس جلا هدف ته را وګرځوئ او محدود لوستونکی رول وازمویئ.'))
], [
project(t('Local enrollment service database','دیتابیس خدمت ثبت‌نام محلی','د محلي نوم‌لیکنې خدمت ډیټابېس'),t('Enforce course capacity with two competing local clients.','ظرفیت کورس را با دو مشتری محلی هم‌زمان تضمین کنید.','د کورس ظرفیت له دوو هممهاله محلي مشتریانو سره تضمین کړئ.'),[t('Use stable enrollment keys and constraints.','کلید ثابت ثبت‌نام و محدودیت استفاده کنید.','ثابت نوم‌لیکنې کلي او محدودیتونه وکاروئ.'),t('Test the last available seat with two sessions.','آخرین چوکی را با دو جلسه آزمایش کنید.','وروستۍ څوکۍ په دوو ناستو وازمویئ.'),t('Explain rollback and retry behavior.','رفتار لغو و تلاش دوباره را توضیح بدهید.','لغوه کول او بیا هڅه تشریح کړئ.')]),
project(t('Expense reporting database','دیتابیس گزارش مصرف','د لګښت راپور ډیټابېس'),t('Produce grouped and running totals for fictional expenses.','برای مصرف فرضی مجموع گروهی و جاری بسازید.','د فرضي لګښت لپاره ډله ییزې او روانې مجموعې جوړې کړئ.'),[t('Use an exact numeric amount contract.','قرارداد مبلغ عددی دقیق استفاده کنید.','د دقیق عددي مبلغ تړون وکاروئ.'),t('Use deterministic window ordering.','ترتیب ثابت پنجره استفاده کنید.','د کړکۍ ثابت ترتیب وکاروئ.'),t('Compare query plans without changing totals.','طرح‌ها را بدون تغییر مجموع مقایسه کنید.','پلانونه بې مجموعې بدلولو پرتله کړئ.')]),
project(t('Restore rehearsal','تمرین بازیابی','د راګرځولو تمرین'),t('Deliver a local dump and verified restoration using restricted roles.','آرشیف محلی و بازیابی بررسی‌شده با نقش محدود تحویل بدهید.','محلي ارشیف او په محدود رول کتل شوې راګرځونه وسپارئ.'),[t('Restore into a separate training database.','در دیتابیس تمرینی جدا بازیابی کنید.','جلا تمریني ډیټابېس ته را وګرځوئ.'),t('Verify constraints and report totals after restore.','پس از بازیابی محدودیت و مجموع گزارش را بررسی کنید.','له راګرځولو وروسته محدودیت او مجموعې وګورئ.'),t('Show that the reader cannot modify records.','نشان بدهید خواننده ثبت را تغییر داده نمی‌تواند.','وښيئ چې لوستونکی ثبتونه نه شي بدلولای.')])])

c('mongodb',t('MongoDB and Document Databases','MongoDB و دیتابیس سندی','MongoDB او سندي ډیټابېسونه'),'database-foundations',MONGO,[
module(t('Documents and collections','سند و مجموعه','سند او ټولګه'),t('A document stores named fields together, while a collection groups documents. Think of one library book with a title and a list of tags. MongoDB stores BSON documents; the shell uses JavaScript-like notation to express them. Flexible fields do not mean that a program can safely accept any shape.', 'سند فیلدهای نام‌دار را یک‌جا و مجموعه سندها را گروه می‌کند. کتابی با عنوان و فهرست برچسب تصور کنید. MongoDB سند BSON ذخیره می‌کند و shell نوشتار شبیه JavaScript دارد. انعطاف فیلد به معنی پذیرش امن هر ساختار نیست.', 'سند نوم لرونکې خانې یوځای او ټولګه سندونه ډله کوي. د نوم او نښو لېست لرونکی کتاب تصور کړئ. MongoDB د BSON سند ساتي او shell د JavaScript په شان لیکنه لري. د خانو نرموالی د هر جوړښت خوندي منل نه دي.'),'db.books.insertOne({_id:1,title:"Python",tags:["coding","beginner"]});\ndb.books.find({_id:1},{_id:0,title:1,tags:1});',t('insertOne creates one document with a fixed training id. find matches that id and the projection hides _id while returning title and tags. Repeating the insert unchanged fails on the duplicate id. Use a fresh training collection rather than silently overwriting someone else\'s data.','insertOne با شناسهٔ ثابت تمرینی سند می‌سازد. find همان را می‌گیرد و projection شناسه را پنهان و عنوان و برچسب را می‌دهد. تکرار درج با همان شناسه خطا می‌دهد. مجموعهٔ تازهٔ تمرینی استفاده کنید، نه بازنویسی خاموش معلومات دیگران.','insertOne په ثابت تمریني پېژند سند جوړوي. find هماغه اخلي او projection پېژند پټوي، نوم او نښې ورکوي. په هماغه پېژند بیا داخلول خطا ورکوي. تازه تمریني ټولګه وکاروئ، د بل معلومات په پټه مه بدلوئ.'),t('Create a second book with a distinct id and find only its title.','کتاب دوم با شناسهٔ جدا بسازید و فقط عنوانش را بخوانید.','دویم کتاب په بېل پېژند جوړ او یوازې نوم یې ولولئ.')),
module(t('Filters and targeted updates','فلتر و تغییر هدفمند','چاڼ او هدفمن بدلون'),t('A filter describes which documents match. An update operator changes selected fields rather than replacing the whole document. Match by a stable identity when editing one record. Check matched and modified counts; a command that matched nothing is not evidence that the intended book changed.', 'فلتر سند مطابق را مشخص می‌کند. عملگر تغییر فیلد انتخابی را عوض می‌کند، نه تمام سند را. برای ویرایش یک ثبت هویت ثابت بگیرید. تعداد مطابق و تغییرکرده را ببینید؛ صفر مطابق ثابت نمی‌کند کتاب هدف تغییر کرده است.', 'چاڼ برابر سندونه ټاکي. د بدلون عملګر ټاکلې خانې بدلوي، ټول سند نه بدلوي. د یوه ثبت سمون ته ثابت هویت وکاروئ. برابر او بدل شوي شمېر وګورئ؛ صفر برابر د هدف کتاب بدلون نه ثابتوي.'),'db.items.insertOne({_id:1,name:"Notebook",stock:5});\ndb.items.updateOne({_id:1,stock:{$gte:2}},{$inc:{stock:-2}});\ndb.items.find({_id:1});',t('The inserted stock is 5. The filter requires at least 2, then $inc subtracts 2 atomically within this document, leaving 3. A request for more than available should match zero documents. This protects a single-document stock rule, not a separate sale record in another collection.','موجودی اول 5 است. شرط حداقل 2 می‌خواهد و $inc در همین سند 2 کم می‌کند؛ 3 می‌ماند. درخواست بیش از موجودی باید صفر مطابق بدهد. این قاعدهٔ یک سند است، نه ثبت فروش جدا در مجموعهٔ دیگر.','لومړنۍ موجودي 5 ده. شرط لږ تر لږه 2 غواړي او $inc په همدې سند کې 2 کموي؛ 3 پاتې کېږي. له موجودۍ ډېر غوښتل باید صفر برابر ورکړي. دا د یوه سند قاعده ساتي، په بله ټولګه کې جلا پلور نه.'),t('Attempt an oversized decrement and verify the stock remains unchanged.','کاهش بیش از موجودی را امتحان و ثابت ماندن مقدار را بررسی کنید.','له موجودۍ ډېر کمول وازمویئ او ثابت مقدار وګورئ.')),
module(t('Embedding and references','جاسازی و ارجاع','دننه ساتل او اشارې'),t('Embed data read together when its size and lifetime fit the parent. Use references for independent or growing records. Copying a student name into every enrollment can make updates inconsistent. There is no universal rule that every relationship should be embedded; start from access patterns and update behavior.', 'معلومات هم‌خواندنی را وقتی اندازه و عمر مناسب دارند داخل والد بگذارید. برای ثبت مستقل یا رو به رشد ارجاع استفاده کنید. کاپی نام شاگرد در هر ثبت‌نام تغییر را ناسازگار می‌کند. هر رابطه نباید جاسازی شود؛ از روش خواندن و تغییر آغاز کنید.', 'یوځای لوستل کېدونکي معلومات چې اندازه او عمر یې مناسب وي، دننه وساتئ. خپلواک یا لویېدونکي ثبت ته اشاره وکاروئ. په هره نوم‌لیکنه کې د نوم کاپي بدلون ناسازګاروي. هره اړیکه دننه نه ساتل کېږي؛ له لوستلو او بدلون پیل وکړئ.'),'db.courses.insertOne({_id:1,title:"SQL",lessons:[{title:"Tables"},{title:"Queries"}]});\ndb.courses.find({_id:1},{lessons:1,_id:0});',t('The course document embeds two small lesson summaries and reads them together. It does not create a separate lessons collection. If lessons become large independently edited records, consider references instead. Explain who owns each update before deciding which model is easier to maintain.','سند کورس دو خلاصهٔ کوچک درس را داخل خود نگه می‌دارد و یک‌جا می‌خواند. مجموعهٔ درس جدا نمی‌سازد. اگر درس‌ها بزرگ و مستقل ویرایش شوند، ارجاع را بررسی کنید. پیش از انتخاب مدل مالک هر تغییر را مشخص کنید.','د کورس سند دوه واړه درسي لنډیزونه دننه ساتي او یوځای لولي. جلا درسي ټولګه نه جوړوي. که درسونه لوی او خپلواک سمېږي، اشارې وڅېړئ. د ماډل له ټاکلو مخکې د هر بدلون مالک وټاکئ.'),t('Compare embedded lesson summaries with referenced full lesson documents.','خلاصهٔ جاسازی‌شده را با سند کامل ارجاعی مقایسه کنید.','دننه لنډیزونه له اشاره شوو بشپړو درسونو سره پرتله کړئ.')),
module(t('Aggregation pipelines','مراحل تجمیع','د راټولولو پړاوونه'),t('A pipeline passes documents through ordered stages. Match narrows the input, group produces summaries, and sort orders the result. Each stage changes what the next stage receives. Write down an intermediate result after each stage instead of guessing from the final pipeline alone.', 'پایپ‌لاین سندها را از مرحله‌های مرتب می‌گذراند. match ورودی را کم، group خلاصه و sort ترتیب می‌دهد. هر مرحله ورودی بعدی را تغییر می‌دهد. بعد هر مرحله نتیجهٔ میانی بنویسید؛ تنها از متن نهایی حدس نزنید.', 'پایپ لاین سندونه له مرتبو پړاوونو تېروي. match داخله کموي، group لنډیز او sort ترتیب ورکوي. هر پړاو د بل داخله بدلوي. له هر پړاو وروسته منځنۍ پایله ولیکئ؛ یوازې له وروستي متن اټکل مه کوئ.'),'db.expenses.insertMany([{category:"books",amount:20},{category:"books",amount:10},{category:"travel",amount:5}]);\ndb.expenses.aggregate([{$group:{_id:"$category",total:{$sum:"$amount"}}},{$sort:{_id:1}}]);',t('Three expense documents become two grouped documents. books totals 30 and travel totals 5; sorting by group id makes the order explicit. The pipeline reads records and does not rewrite the expenses. Running the fixture insertion twice would double the totals, so begin with a fresh collection.','سه سند مصرف دو گروه می‌شوند. books مجموع 30 و travel مجموع 5 دارد؛ ترتیب شناسهٔ گروه صریح است. پایپ‌لاین مصرف را بازنویسی نمی‌کند. درج نمونه برای بار دوم مجموع را دو برابر می‌کند؛ از مجموعهٔ تازه آغاز کنید.','درې لګښت سندونه دوه ډلې کېږي. books د 30 او travel د 5 مجموعه لري؛ د ډلې پېژند ترتیب څرګند دی. پایپ لاین لګښت نه بیا لیکي. د نمونې بیا داخلول مجموعې دوه برابروي؛ له تازه ټولګې پیل کړئ.'),t('Add a category filter before grouping and trace which records remain.','پیش از گروه‌بندی فلتر کتگوری اضافه و ثبت باقی را دنبال کنید.','له ډلې مخکې کتګوري چاڼ زیات او پاتې ثبتونه تعقیب کړئ.')),
module(t('Validation and indexes','بررسی و اندکس','کتنه او اندکس'),t('Flexible documents still need a contract. Validation can require fields and types. A unique index rejects duplicate key values, while an ordinary index only helps access. Existing invalid or duplicate data can prevent adding a new rule; inspect a training copy before changing a real collection.', 'سند انعطاف‌پذیر هنوز قرارداد می‌خواهد. بررسی می‌تواند فیلد و نوع را لازم سازد. اندکس یکتا تکرار کلید را رد و اندکس عادی فقط دسترسی را کمک می‌کند. معلومات خراب قبلی می‌تواند افزودن قاعده را ناکام سازد؛ نخست کاپی تمرینی را بررسی کنید.', 'نرم سند لا تړون غواړي. کتنه خانې او ډولونه اړین کولای شي. یکتا اندکس تکراري کلی ردوي، عادي اندکس یوازې لاسرسی ښه کوي. زاړه خراب معلومات نوی قاعده ناکامولای شي؛ لومړی تمریني کاپي وګورئ.'),'db.members.createIndex({studentId:1},{unique:true});\ndb.members.insertOne({studentId:"S1",name:"Amina"});\ndb.members.find({studentId:"S1"});',t('The index makes studentId unique in this collection. The inserted record can be found by S1. A second S1 is rejected, but the index does not by itself require a meaningful name or a particular studentId format. Add schema validation and test missing fields separately.','اندکس studentId را در مجموعه یکتا می‌سازد و ثبت با S1 پیدا می‌شود. S1 دوم رد است، اما نام معنی‌دار یا قالب شناسه را تضمین نمی‌کند. بررسی ساختار اضافه و فیلد ناموجود را جدا آزمایش کنید.','اندکس studentId په ټولګه کې یکتا کوي او ثبت په S1 موندل کېږي. دویم S1 رد دی، خو مانا لرونکی نوم یا پېژند بڼه نه تضمینوي. د جوړښت کتنه ورزیاته او ورکې خانې جلا وازمویئ.'),t('Test duplicate identities and missing required fields as separate failures.','هویت تکراری و فیلد لازم ناموجود را دو ناکامی جدا آزمایش کنید.','تکراري هویت او ورک اړین فیلډونه جلا ناکامۍ وازمویئ.')),
module(t('Atomicity and local backup','یک‌پارچگی و پشتیبان محلی','اټومي بدلون او محلي بیک اپ'),t('A single-document update is atomic. Changes across several documents need a different design or a supported transaction deployment. A standalone server does not support multi-document transactions; a local replica set can be provisioned for that lesson. Backups still need restore testing, even when individual writes are atomic.', 'تغییر یک سند یک‌پارچه است. چند سند طراحی دیگر یا محیط پشتیبان معامله می‌خواهد. سرور standalone معاملهٔ چندسندی ندارد؛ replica set محلی را می‌توان آماده کرد. حتی با نوشتن یک‌پارچه، پشتیبان آزمون بازیابی می‌خواهد.', 'د یوه سند بدلون اټومي دی. څو سندونه بله طرحه یا ملاتړ شوی معاملاتي چاپېریال غواړي. standalone سرور څو سندي معامله نه مني؛ محلي replica set برابرېدای شي. حتی اټومي لیکنه بیک اپ د راګرځولو ازموینې نه بې نیازوي.'),'// Shell commands, not mongosh JavaScript; training databases only.\nmongodump --db training_source --out training_backup\nmongorestore --nsFrom="training_source.*" --nsTo="training_restore.*" training_backup',t('The dump writes a local backup and the restore maps it to a different training database name. A changing source requires a consistency plan; these commands alone do not prove a cross-collection snapshot. Compare counts and reports after restoring, and never present an untested archive as guaranteed recovery.','آرشیف محلی نوشته و در نام دیتابیس تمرینی دیگر بازگردانده می‌شود. منبع در حال تغییر برنامهٔ سازگاری می‌خواهد؛ دستورها عکس سازگار چندمجموعه‌ای را تضمین نمی‌کنند. تعداد و گزارش را مقایسه کنید و آرشیف آزمایش‌نشده را بازیابی تضمینی ننامید.','محلي بیک اپ لیکل او بل تمریني ډیټابېس نوم ته راګرځول کېږي. بدلېدونکې سرچینه د سازګارۍ پلان غواړي؛ قوماندې د څو ټولګو برابر snapshot نه تضمینوي. شمېر او راپور پرتله کړئ او نازمویل شوی ارشیف تضمین شوې راګرځونه مه ګڼئ.'),t('Restore fictional documents to a separate database and explain consistency limits.','سند فرضی را در دیتابیس جدا برگردانید و محدودیت سازگاری را توضیح بدهید.','فرضي سندونه جلا ډیټابېس ته را وګرځوئ او د سازګارۍ حدود ووایئ.'))
], [
project(t('Learning resource catalog','فهرست منابع آموزشی','د زده کړې سرچینو فهرست'),t('Store fictional learning resources with tags and searchable titles.','منبع آموزشی فرضی با برچسب و عنوان جستجوشدنی ذخیره کنید.','فرضي زده کړیزې سرچینې له نښو او لټېدونکو نومونو سره وساتئ.'),[t('Validate required fields and stable identifiers.','فیلد لازم و شناسهٔ ثابت را بررسی کنید.','اړینې خانې او ثابت پېژندونه وګورئ.'),t('Compare embedding and referencing for lesson metadata.','جاسازی و ارجاع مشخصات درس را مقایسه کنید.','د درس معلوماتو دننه ساتل او اشارې پرتله کړئ.'),t('Demonstrate tag filters and deterministic result ordering.','فلتر برچسب و ترتیب ثابت نتیجه را نشان بدهید.','د نښو چاڼ او ثابت پایله ترتیب وښيئ.')]),
project(t('Document expense reports','گزارش مصرف سندی','سندي لګښت راپورونه'),t('Aggregate fictional expenses and keep invalid records out.','مصرف فرضی را تجمیع و ثبت خراب را منع کنید.','فرضي لګښت راټول او خراب ثبت منع کړئ.'),[t('Validate amount types and nonnegative values.','نوع مبلغ و غیرمنفی بودن را بررسی کنید.','د مبلغ ډول او غیرمنفي والی وګورئ.'),t('Trace every stage of a grouped report.','هر مرحلهٔ گزارش گروهی را دنبال کنید.','د ډله ییز راپور هر پړاو تعقیب کړئ.'),t('Test empty categories and repeated fixture setup.','کتگوری خالی و آماده‌سازی تکراری نمونه را آزمایش کنید.','تشه کتګوري او تکراري نمونه جوړول وازمویئ.')]),
project(t('Local document recovery lab','کارگاه بازیابی سند محلی','د محلي سند راګرځولو تمرین'),t('Practice consistent local backup and restore with fictional collections.','پشتیبان و بازیابی سازگار را با مجموعهٔ فرضی تمرین کنید.','په فرضي ټولګو برابر محلي بیک اپ او راګرځول تمرین کړئ.'),[t('Restore to a separate target namespace.','در فضای نام مقصد جدا بازیابی کنید.','جلا هدف نوم فضا ته را وګرځوئ.'),t('Compare document counts and report totals.','تعداد سند و مجموع گزارش را مقایسه کنید.','د سند شمېر او راپور مجموعې پرتله کړئ.'),t('Document standalone and replica-set transaction differences.','تفاوت معاملهٔ standalone و replica set را ثبت کنید.','د standalone او replica set معاملې توپیر ثبت کړئ.')])])

# Normalize the one parallel row written in the opposite order.
_key = COURSES[0]['modules'][0]['trace']
TEXT[_key]['fa'], TEXT[_key]['ps'] = TEXT[_key]['ps'], TEXT[_key]['fa']

def beginner(c):
    m=c['modules'][0]
    result=dict(terms=[
        t('Database: organized information that a program can read and change.','دیتابیس: معلومات منظم که پروگرام خوانده و تغییر داده می‌تواند.','ډیټابېس: منظم معلومات چې پروګرام یې لوستلای او بدلولای شي.'),
        t('Record: one stored item, represented by a row or a document.','ثبت: یک مورد ذخیره‌شده به شکل سطر یا سند.','ثبت: یو ساتل شوی توکی، د کتار یا سند په بڼه.'),
        t('Query: a request describing which information you want.','پرس‌وجو: درخواستی که معلومات خواسته‌شده را مشخص می‌کند.','پوښتنه: غوښتنه چې غوښتل شوي معلومات ټاکي.'),
        t('Constraint: a rule that rejects invalid stored data.','محدودیت: قاعده‌ای که معلومات ذخیره‌شدنی نامعتبر را رد می‌کند.','محدودیت: قاعده چې ناسم ساتل کېدونکي معلومات ردوي.')],before=m['explanation'],code=m['code'],trace=[m['trace']],
        question=t('What should you do before changing training data?', 'پیش از تغییر معلومات تمرینی چه باید کرد؟', 'د تمریني معلوماتو له بدلولو مخکې څه وکړئ؟'),
        options=[t('Predict the result and identify the target records.','نتیجه را پیش‌بینی و ثبت هدف را مشخص کنید.','پایله اټکل او هدف ثبتونه وټاکئ.'),t('Assume every command changes only one row.','فرض کنید هر دستور فقط یک سطر را تغییر می‌دهد.','فرض کړئ هره قومانده یوازې یو کتار بدلوي.'),t('Use the learner progress database for experiments.','دیتابیس پیشرفت شاگرد را برای تجربه استفاده کنید.','د زده کوونکي د پرمختګ ډیټابېس د تجربې لپاره وکاروئ.')],answer=0,
        task=m['task'],hint=t('Use a fresh fictional fixture. Read the worked trace and change only the requested fields or query.', 'نمونهٔ فرضی تازه استفاده کنید. شرح مثال را بخوانید و فقط فیلد یا پرس‌وجوی خواسته‌شده را تغییر بدهید.', 'تازه فرضي نمونه وکاروئ. د مثال تشریح ولولئ او یوازې غوښتل شوې خانې یا پوښتنه بدله کړئ.'),solution=m['code'],result=m['trace'])
    if c['id']=='database-foundations':
        result['solution']=BOOKS+'SELECT title FROM books ORDER BY id;'
        result['result']=t('Three titles appear in this order: Python, Databases, Web. No price column is returned.','سه عنوان به این ترتیب دیده می‌شود: Python، Databases، Web. ستون قیمت برنمی‌گردد.','درې نومونه په دې ترتیب ښکاري: Python، Databases، Web. د بیې ستنه نه راځي.')
    elif c['id']=='sql':
        result['solution']=BOOKS+'SELECT id,title AS book_name FROM books ORDER BY id;'
        result['result']=t('The columns are id and book_name. The ordered rows are 1/Python, 2/Databases, and 3/Web.','ستون‌ها id و book_name اند. سطرها 1/Python، 2/Databases و 3/Web اند.','ستنې id او book_name دي. کتارونه 1/Python، 2/Databases او 3/Web دي.')
    elif c['id']=='sqlite':
        result['task']=t('Count the books in the fresh fixture and explain what closing an in-memory connection does.','کتاب نمونهٔ تازه را بشمارید و اثر بستن اتصال حافظه را توضیح بدهید.','د تازه نمونې کتابونه وشمېرئ او د حافظوي اتصال د تړلو اغېز ووایئ.')
    elif c['id']=='mongodb':
        result['solution']='db.books.insertOne({_id:2,title:"Databases",tags:["data"]});\ndb.books.find({_id:2},{_id:0,title:1});'
        result['result']=t('One result document contains title: Databases. The first book is unchanged.','یک سند نتیجه عنوان Databases دارد. کتاب اول تغییر نمی‌کند.','یوه پایله د Databases نوم لري. لومړی کتاب نه بدلېږي.')
    return result

def append_database_courses(course, guides):
    for item in COURSES:
        course(item['id'],item['title'],item['prerequisites'],item['tools'],[(m['title'],m['explanation'],m['code'],m['task']) for m in item['modules']],item['projects'])
        guides[item['id']]=beginner(item)

def install_translations(modules,projects,tools,beginners,ui):
    for item in COURSES:
        g=beginner(item)
        for lang in ('fa','ps'):
            tr=lambda value:TEXT[value][lang]
            modules.setdefault(item['id'],{})[lang]=[(tr(m['title']),tr(m['explanation']),tr(m['task'])) for m in item['modules']]
            projects.setdefault(item['id'],{})[lang]=[(tr(p[0]),tr(p[1]),*[tr(r) for r in p[2]]) for p in item['projects']]
            tools.setdefault(item['id'],{})[lang]=tr(item['tools'])
            beginners.setdefault(item['id'],{})[lang]=[tr(s) for s in [*g['terms'],g['before'],*g['trace'],g['question'],g['task'],g['hint'],g['result']]]
    ui.extend((key,values['fa'],values['ps']) for key,values in TEXT.items())
